"""Regenerate the processor + controller-service *catalogs* from a running NiFi.

NiFi exposes every available processor / controller-service type via its REST
API; this module pulls that list and emits two generated modules:

* ``niflow/processors/catalog.py`` — one thin factory per processor type
  (hundreds of them), plus ``ALL`` / ``TYPES`` / ``RESTRICTED`` / ``DEPRECATED``
  registries you can iterate over.
* ``niflow/services/catalog.py`` — same shape for controller services.

The hand-curated factories in :mod:`niflow.processors.standard` /
:mod:`niflow.services.standard` carry sensible default properties and stay the
*preferred* entry points; the generated catalog is the exhaustive type-only
shell — useful as a registry, for catalog tests, and so callers don't have to
hand-type fully-qualified class names.

Run it::

    python -m niflow.codegen        # needs a reachable NiFi (see niflow.config)

or ``make catalog``. The generator overwrites the catalog files in place; treat
them as build artefacts that just happen to be committed for offline imports.
"""
from __future__ import annotations

import keyword
import re
from collections import defaultdict
from pathlib import Path
from types import SimpleNamespace
from typing import Any, List, Optional, Tuple

from niflow.config import NiFiConfig
from niflow.utils import get_logger

logger = get_logger()

# Where the generated files live, derived from this module's location so the
# script works regardless of CWD.
_NIFLOW_ROOT = Path(__file__).resolve().parent
PROCESSORS_CATALOG_PATH = _NIFLOW_ROOT / "processors" / "catalog.py"
SERVICES_CATALOG_PATH = _NIFLOW_ROOT / "services" / "catalog.py"

# Temp group + client id used while harvesting the rulebook (relationships /
# descriptors). NiFi only exposes these once a type is instantiated, so we
# create one of each in a throwaway group, read them back, and delete the group.
_HARVEST_GROUP = "__niflow_harvest__"
_CLIENT_ID = "niflow-codegen"


# --- name sanitisation ------------------------------------------------------

_IDENT_RE = re.compile(r"[^0-9a-zA-Z_]")


def _simple_name(fqcn: str) -> str:
    """``org.apache.nifi.processors.standard.PutFile`` -> ``PutFile``."""
    return fqcn.rsplit(".", 1)[-1]


def _artifact_stem(bundle: Any) -> str:
    """Short, identifier-safe tail of the bundle artifact (e.g. ``kafka_3``)."""
    artifact = getattr(bundle, "artifact", "") or ""
    # Strip "nifi-" prefix and "-nar" suffix that almost every NAR carries.
    trimmed = re.sub(r"^nifi-", "", artifact)
    trimmed = re.sub(r"-nar$", "", trimmed)
    return _IDENT_RE.sub("_", trimmed).strip("_") or "ext"


def _safe_identifier(raw: str) -> str:
    """Coerce *raw* into a valid (non-keyword) Python identifier."""
    out = _IDENT_RE.sub("_", raw)
    if not out or not (out[0].isalpha() or out[0] == "_"):
        out = "_" + out
    if keyword.iskeyword(out):
        out += "_"
    return out


def _unique_factory_names(items: List[Any]) -> List[Tuple[str, Any]]:
    """Return ``[(factory_name, item), ...]`` with every factory name unique.

    Strategy: try the simple class name first; on collision, suffix with the
    bundle artifact stem; if even that collides, append a counter. Items are
    paired with the same ``DocumentedTypeDTO`` they came from.

    Items already sharing a fully-qualified type (same FQCN in two bundles)
    are de-duplicated up front — only the first is emitted, and the duplicate
    fact is logged. niflow's deploy can't pick a side for an ambiguous FQCN
    anyway (``_resolve_type`` would raise), so the catalog matches reality.
    """
    by_fqcn: dict = defaultdict(list)
    for it in items:
        by_fqcn[it.type].append(it)
    for fqcn, dupes in by_fqcn.items():
        if len(dupes) > 1:
            logger.warning(
                "FQCN %r appears in %d bundles; keeping first, dropping the rest",
                fqcn, len(dupes),
            )

    deduped = [dupes[0] for dupes in by_fqcn.values()]
    deduped.sort(key=lambda it: it.type)

    used: set = set()
    out: List[Tuple[str, Any]] = []
    for it in deduped:
        base = _safe_identifier(_simple_name(it.type))
        candidate = base
        if candidate in used:
            candidate = _safe_identifier(f"{base}_{_artifact_stem(it.bundle)}")
        n = 2
        while candidate in used:
            candidate = f"{base}_{n}"
            n += 1
        used.add(candidate)
        out.append((candidate, it))
    return out


# --- file emission ----------------------------------------------------------

_HEADER = '''"""AUTO-GENERATED by ``python -m niflow.codegen`` — do not edit by hand.

Exhaustive catalog of {kind} types reported by the NiFi instance this was
generated against. Each factory is a thin shell over the type string; for
sensible defaults prefer the curated factories in :mod:`{curated}`.

Regenerate after upgrading NiFi or installing new NARs::

    python -m niflow.codegen
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from {curated} import {helper}
from {component_mod} import {component_cls}
'''


def _emit_processor_factory(factory_name: str, fqcn: str) -> str:
    return (
        f"def {factory_name}(name: str = {factory_name!r}, "
        f"properties: Optional[Dict[str, Any]] = None, **settings: Any) -> {{cls}}:\n"
        f"    return _processor({fqcn!r}, name, properties=properties, **settings)\n\n"
    ).replace("{cls}", "Processor")


def _emit_service_factory(factory_name: str, fqcn: str) -> str:
    return (
        f"def {factory_name}(name: str = {factory_name!r}, "
        f"properties: Optional[Dict[str, Any]] = None) -> ControllerService:\n"
        f"    return _service({fqcn!r}, name, properties=properties)\n\n"
    )


def _emit_registries(named: List[Tuple[str, Any]]) -> str:
    """Produce the ``ALL`` / ``TYPES`` / ``RESTRICTED`` / ``DEPRECATED`` block."""
    all_list = ",\n    ".join(name for name, _ in named)
    types_list = ",\n    ".join(repr(it.type) for _, it in named)
    restricted = sorted(it.type for _, it in named if getattr(it, "restricted", False))
    deprecated = sorted(
        it.type for _, it in named if getattr(it, "deprecation_reason", None)
    )

    out = []
    out.append("ALL = [\n    " + all_list + ",\n]\n\n")
    out.append("TYPES = [\n    " + types_list + ",\n]\n\n")
    out.append(
        "RESTRICTED = {\n    "
        + (",\n    ".join(repr(t) for t in restricted) + ",\n" if restricted else "")
        + "}\n\n"
    )
    out.append(
        "DEPRECATED = {\n    "
        + (",\n    ".join(repr(t) for t in deprecated) + ",\n" if deprecated else "")
        + "}\n"
    )
    return "".join(out)


def _emit_bundles(named: List[Tuple[str, Any]]) -> str:
    """Produce the ``BUNDLES`` map: ``type -> {group, artifact, version}``.

    This is the authoritative ``type -> NAR`` mapping for the instance this
    catalog was generated against; the formats consult it so each type emits the
    bundle it actually lives in (not every processor is in nifi-standard-nar).
    """
    lines = []
    for _, item in named:
        bundle = item.bundle
        lines.append(
            f"    {item.type!r}: "
            f"{{'group': {bundle.group!r}, 'artifact': {bundle.artifact!r}, "
            f"'version': {bundle.version!r}}},"
        )
    return "BUNDLES = {\n" + "\n".join(lines) + ("\n" if lines else "") + "}\n"


def _emit_relationships(rules: dict) -> str:
    """Produce the ``RELATIONSHIPS`` map: ``type -> [relationship names]``.

    The harvested rulebook the validator uses to check that every relationship
    is either connected or auto-terminated — completely, not heuristically.
    """
    lines = [
        f"    {type_str!r}: {sorted(rule.get('relationships', []))!r},"
        for type_str, rule in sorted(rules.items())
    ]
    return "RELATIONSHIPS = {\n" + "\n".join(lines) + ("\n" if lines else "") + "}\n"


def _emit_descriptors(rules: dict) -> str:
    """Produce the ``DESCRIPTORS`` map: ``type -> {prop -> {required, allowable, ...}}``.

    The harvested property rulebook the validator uses to flag missing required
    properties and out-of-range (non-allowable) values.
    """
    lines = []
    for type_str, rule in sorted(rules.items()):
        descriptors = rule.get("descriptors") or {}
        if descriptors:
            lines.append(f"    {type_str!r}: {descriptors!r},")
    return "DESCRIPTORS = {\n" + "\n".join(lines) + ("\n" if lines else "") + "}\n"


def _render(
    kind: str,
    curated_mod: str,
    helper: str,
    component_mod: str,
    component_cls: str,
    named: List[Tuple[str, Any]],
    emit_factory,
    extra: str = "",
) -> str:
    header = _HEADER.format(
        kind=kind, curated=curated_mod, helper=helper,
        component_mod=component_mod, component_cls=component_cls,
    )
    body = "".join(emit_factory(name, item.type) for name, item in named)
    rendered = header + "\n" + body + _emit_registries(named) + "\n" + _emit_bundles(named)
    return rendered + ("\n" + extra if extra else "")


# --- public entrypoints -----------------------------------------------------

def _to_documented_type(dto: dict) -> SimpleNamespace:
    """Adapt a REST ``DocumentedTypeDTO`` dict to the attribute shape we render."""
    bundle = dto.get("bundle") or {}
    return SimpleNamespace(
        type=dto.get("type", ""),
        bundle=SimpleNamespace(
            group=bundle.get("group", ""),
            artifact=bundle.get("artifact", ""),
            version=bundle.get("version", ""),
        ),
        restricted=bool(dto.get("restricted", False)),
        deprecation_reason=dto.get("deprecationReason"),
    )


def _trim_descriptors(descriptors: Optional[dict]) -> dict:
    """Keep only the descriptor facts the validator can act on.

    A property is worth recording if it's required, constrains values (an enum),
    is conditionally required (dependencies), or references a controller service.
    Plain optional free-text properties carry no validation signal, so we drop
    them to keep the emitted catalog small.
    """
    out: dict = {}
    for name, d in (descriptors or {}).items():
        entry: dict = {}
        if d.get("required"):
            entry["required"] = True
        default = d.get("defaultValue")
        if default not in (None, ""):
            entry["default"] = default
        allowable = [
            a["allowableValue"]["value"]
            for a in (d.get("allowableValues") or [])
            if a.get("allowableValue")
        ]
        if allowable:
            entry["allowable"] = allowable
        service = d.get("identifiesControllerService")
        if service:
            entry["service"] = service
        dependencies = [
            {"property": dep.get("propertyName"),
             "values": list(dep.get("dependentValues") or [])}
            for dep in (d.get("dependencies") or [])
        ]
        if dependencies:
            entry["dependencies"] = dependencies
        if entry:
            out[name] = entry
    return out


def _harvest_rules(client: Any, proc_types: List[Any]) -> dict:
    """Instantiate one of each processor type to read its relationships.

    NiFi has no "describe type X" endpoint — relationships (and property
    descriptors) only appear once a processor exists. So we spin up a throwaway
    group, create one processor per type (the create response already carries the
    component's relationships), and delete the group. Best-effort: a type that
    can't be instantiated (restricted, needs setup) is simply skipped, and the
    validator falls back to its heuristic for it.

    Returns ``{type: {"relationships": [...]}}``.
    """
    rules: dict = {}
    root = client.root_id()
    group = client._request(
        "POST", f"/process-groups/{root}/process-groups",
        json={"revision": {"version": 0, "clientId": _CLIENT_ID},
              "component": {"name": _HARVEST_GROUP, "position": {"x": 0.0, "y": 0.0}}},
    ).json()
    group_id = group["id"]
    logger.info("Harvesting rules from %d types into temp group %s", len(proc_types), group_id)
    try:
        for i, dt in enumerate(proc_types):
            try:
                resp = client._request(
                    "POST", f"/process-groups/{group_id}/processors",
                    json={"revision": {"version": 0, "clientId": _CLIENT_ID},
                          "component": {
                              "type": dt.type,
                              "bundle": {"group": dt.bundle.group,
                                         "artifact": dt.bundle.artifact,
                                         "version": dt.bundle.version},
                              "position": {"x": 0.0, "y": float(i)}}},
                ).json()
                component = resp.get("component", {})
                rules[dt.type] = {
                    "relationships": [r["name"] for r in component.get("relationships", [])],
                    "descriptors": _trim_descriptors(
                        (component.get("config") or {}).get("descriptors")
                    ),
                }
            except Exception as exc:  # restricted / un-instantiable type — skip it
                logger.warning("Skipped %s while harvesting: %s", dt.type, exc)
    finally:
        try:
            version = client._pg_entity(group_id)["revision"]["version"]
            client._request(
                "DELETE", f"/process-groups/{group_id}",
                params={"version": version, "clientId": _CLIENT_ID,
                        "disconnectedNodeAcknowledged": "false"},
            )
            logger.info("Removed temp harvest group %s", group_id)
        except Exception as exc:  # don't leave it behind silently
            logger.error("Could not delete temp harvest group %s: %s", group_id, exc)
    return rules


def _fetch(client: Any) -> Tuple[List[Any], List[Any]]:
    """Return ``(processor_types, controller_service_types)`` from the live NiFi.

    Uses the version-agnostic REST endpoints, so this works on 1.x and 2.x —
    including instances with custom NARs installed.
    """
    procs = client._get_json("/flow/processor-types").get("processorTypes", [])
    svcs = client._get_json("/flow/controller-service-types").get(
        "controllerServiceTypes", []
    )
    return (
        [_to_documented_type(d) for d in procs],
        [_to_documented_type(d) for d in svcs],
    )


def generate(
    config: Optional[NiFiConfig] = None, *, harvest: bool = True
) -> Tuple[int, int]:
    """Connect to NiFi, regenerate both catalog files, return ``(n_procs, n_svcs)``.

    When ``harvest`` is true (the default) each processor type is briefly
    instantiated to capture its relationships into the ``RELATIONSHIPS`` map the
    validator uses. This creates and deletes a throwaway group, so it needs
    write access; pass ``harvest=False`` for a read-only, relationship-less
    catalog.
    """
    from niflow.client import NiFiClient

    client = NiFiClient(config)
    logger.info("Generating catalogs from NiFi %s", client.version())
    procs, svcs = _fetch(client)
    logger.info("Catalog: %d processors, %d controller services on this NiFi", len(procs), len(svcs))

    proc_named = _unique_factory_names(procs)
    svc_named = _unique_factory_names(svcs)

    rules = _harvest_rules(client, [item for _, item in proc_named]) if harvest else {}

    PROCESSORS_CATALOG_PATH.write_text(
        _render(
            kind="processor",
            curated_mod="niflow.processors.standard",
            helper="_processor",
            component_mod="niflow.core",
            component_cls="Processor",
            named=proc_named,
            emit_factory=_emit_processor_factory,
            extra=_emit_relationships(rules) + "\n" + _emit_descriptors(rules),
        )
    )
    SERVICES_CATALOG_PATH.write_text(
        _render(
            kind="controller-service",
            curated_mod="niflow.services.standard",
            helper="_service",
            component_mod="niflow.core",
            component_cls="ControllerService",
            named=svc_named,
            emit_factory=_emit_service_factory,
        )
    )
    return len(proc_named), len(svc_named)


def main() -> None:
    n_procs, n_svcs = generate(NiFiConfig.from_env())
    print(f"Wrote {PROCESSORS_CATALOG_PATH.relative_to(_NIFLOW_ROOT.parent)}: {n_procs} factories")
    print(f"Wrote {SERVICES_CATALOG_PATH.relative_to(_NIFLOW_ROOT.parent)}: {n_svcs} factories")


if __name__ == "__main__":
    main()
