"""AUTO-GENERATED by ``python -m niflow.codegen --import-defaults`` — do not edit.

What a NiFi line writes onto a component **when it imports a flow**, over and
above the property descriptors' own defaults.

This is not the same thing as the catalog's ``default``. Creating a
``JsonRecordSetWriter`` through the REST API on 2.7.2 gives
``Allow Scientific Notation = 'false'``, exactly as its descriptor says —
but *importing* a flow snapshot that does not mention the property gives
``'true'``, because NiFi preserves the behaviour older flows had. The 1.x twin
is ``schema-protocol-version``. Nothing in niflow emitted those values, and
nothing in the descriptors predicts them, so the differ read them as drift and
planned an unset on every run, forever — and once the applier learned to
actually send removals, that unset became a real write NiFi would immediately
undo.

Harvested by pushing one instance of every type through the real import path
and reading back what the server made of it. Regenerate per line::

    NIFLOW_NIFI_HOST=https://host:8443/nifi-api python -m niflow.codegen --import-defaults

``IMPORT_DEFAULTS`` is keyed by NiFi major version, then type, then property.
"""
from __future__ import annotations

IMPORT_DEFAULTS = {
    1: {
    },
    2: {
        "org.apache.nifi.json.JsonRecordSetWriter": {"Allow Scientific Notation": "true"},
        "org.apache.nifi.processors.aws.credentials.provider.service.AWSCredentialsProviderControllerService": {"Use Anonymous Credentials": "true"},
    },
}
