"""AUTO-GENERATED by ``python -m niflow.codegen`` — do not edit by hand.

Exhaustive catalog of controller-service types reported by the NiFi instance this was
generated against. Each factory is a thin shell over the type string; for
sensible defaults prefer the curated factories in :mod:`niflow.services.standard`.

Regenerate after upgrading NiFi or installing new NARs::

    python -m niflow.codegen
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from niflow.services.standard import _service
from niflow.core import ControllerService

def ApicurioSchemaRegistry(name: str = 'ApicurioSchemaRegistry', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.apicurio.schemaregistry.ApicurioSchemaRegistry', name, properties=properties)

def AvroReader(name: str = 'AvroReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.avro.AvroReader', name, properties=properties)

def AvroRecordSetWriter(name: str = 'AvroRecordSetWriter', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.avro.AvroRecordSetWriter', name, properties=properties)

def AmazonGlueEncodedSchemaReferenceReader(name: str = 'AmazonGlueEncodedSchemaReferenceReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.aws.schemaregistry.AmazonGlueEncodedSchemaReferenceReader', name, properties=properties)

def AmazonGlueSchemaRegistry(name: str = 'AmazonGlueSchemaRegistry', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.aws.schemaregistry.AmazonGlueSchemaRegistry', name, properties=properties)

def DeveloperBoxClientService(name: str = 'DeveloperBoxClientService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.box.controllerservices.DeveloperBoxClientService', name, properties=properties)

def JsonConfigBasedBoxClientService(name: str = 'JsonConfigBasedBoxClientService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.box.controllerservices.JsonConfigBasedBoxClientService', name, properties=properties)

def CEFReader(name: str = 'CEFReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.cef.CEFReader', name, properties=properties)

def ConfluentEncodedSchemaReferenceReader(name: str = 'ConfluentEncodedSchemaReferenceReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.confluent.schemaregistry.ConfluentEncodedSchemaReferenceReader', name, properties=properties)

def ConfluentEncodedSchemaReferenceWriter(name: str = 'ConfluentEncodedSchemaReferenceWriter', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.confluent.schemaregistry.ConfluentEncodedSchemaReferenceWriter', name, properties=properties)

def ConfluentProtobufMessageNameResolver(name: str = 'ConfluentProtobufMessageNameResolver', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.confluent.schemaregistry.ConfluentProtobufMessageNameResolver', name, properties=properties)

def ConfluentSchemaRegistry(name: str = 'ConfluentSchemaRegistry', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.confluent.schemaregistry.ConfluentSchemaRegistry', name, properties=properties)

def StandardAsanaClientProviderService(name: str = 'StandardAsanaClientProviderService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.controller.asana.StandardAsanaClientProviderService', name, properties=properties)

def CSVReader(name: str = 'CSVReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.csv.CSVReader', name, properties=properties)

def CSVRecordSetWriter(name: str = 'CSVRecordSetWriter', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.csv.CSVRecordSetWriter', name, properties=properties)

def StandardDatabaseDialectService(name: str = 'StandardDatabaseDialectService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.database.dialect.service.StandardDatabaseDialectService', name, properties=properties)

def DatabaseTableSchemaRegistry(name: str = 'DatabaseTableSchemaRegistry', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.db.schemaregistry.DatabaseTableSchemaRegistry', name, properties=properties)

def DBCPConnectionPool(name: str = 'DBCPConnectionPool', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.dbcp.DBCPConnectionPool', name, properties=properties)

def DBCPConnectionPoolLookup(name: str = 'DBCPConnectionPoolLookup', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.dbcp.DBCPConnectionPoolLookup', name, properties=properties)

def HikariCPConnectionPool(name: str = 'HikariCPConnectionPool', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.dbcp.HikariCPConnectionPool', name, properties=properties)

def MapCacheClientService(name: str = 'MapCacheClientService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.distributed.cache.client.MapCacheClientService', name, properties=properties)

def SetCacheClientService(name: str = 'SetCacheClientService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.distributed.cache.client.SetCacheClientService', name, properties=properties)

def SetCacheServer(name: str = 'SetCacheServer', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.distributed.cache.server.SetCacheServer', name, properties=properties)

def MapCacheServer(name: str = 'MapCacheServer', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.distributed.cache.server.map.MapCacheServer', name, properties=properties)

def ElasticSearchClientServiceImpl(name: str = 'ElasticSearchClientServiceImpl', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.elasticsearch.ElasticSearchClientServiceImpl', name, properties=properties)

def ElasticSearchLookupService(name: str = 'ElasticSearchLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.elasticsearch.ElasticSearchLookupService', name, properties=properties)

def ElasticSearchStringLookupService(name: str = 'ElasticSearchStringLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.elasticsearch.ElasticSearchStringLookupService', name, properties=properties)

def ExcelReader(name: str = 'ExcelReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.excel.ExcelReader', name, properties=properties)

def StandardFileResourceService(name: str = 'StandardFileResourceService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.fileresource.service.StandardFileResourceService', name, properties=properties)

def GrokReader(name: str = 'GrokReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.grok.GrokReader', name, properties=properties)

def HazelcastMapCacheClient(name: str = 'HazelcastMapCacheClient', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.hazelcast.services.cacheclient.HazelcastMapCacheClient', name, properties=properties)

def EmbeddedHazelcastCacheManager(name: str = 'EmbeddedHazelcastCacheManager', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.hazelcast.services.cachemanager.EmbeddedHazelcastCacheManager', name, properties=properties)

def ExternalHazelcastCacheManager(name: str = 'ExternalHazelcastCacheManager', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.hazelcast.services.cachemanager.ExternalHazelcastCacheManager', name, properties=properties)

def StandardHttpContextMap(name: str = 'StandardHttpContextMap', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.http.StandardHttpContextMap', name, properties=properties)

def JMSConnectionFactoryProvider(name: str = 'JMSConnectionFactoryProvider', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.jms.cf.JMSConnectionFactoryProvider', name, properties=properties)

def JndiJmsConnectionFactoryProvider(name: str = 'JndiJmsConnectionFactoryProvider', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.jms.cf.JndiJmsConnectionFactoryProvider', name, properties=properties)

def JsonPathReader(name: str = 'JsonPathReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.json.JsonPathReader', name, properties=properties)

def JsonRecordSetWriter(name: str = 'JsonRecordSetWriter', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.json.JsonRecordSetWriter', name, properties=properties)

def JsonTreeReader(name: str = 'JsonTreeReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.json.JsonTreeReader', name, properties=properties)

def Kafka3ConnectionService(name: str = 'Kafka3ConnectionService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.kafka.service.Kafka3ConnectionService', name, properties=properties)

def AmazonMSKConnectionService(name: str = 'AmazonMSKConnectionService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.kafka.service.aws.AmazonMSKConnectionService', name, properties=properties)

def KerberosKeytabUserService(name: str = 'KerberosKeytabUserService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.kerberos.KerberosKeytabUserService', name, properties=properties)

def KerberosPasswordUserService(name: str = 'KerberosPasswordUserService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.kerberos.KerberosPasswordUserService', name, properties=properties)

def KerberosTicketCacheUserService(name: str = 'KerberosTicketCacheUserService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.kerberos.KerberosTicketCacheUserService', name, properties=properties)

def StandardPrivateKeyService(name: str = 'StandardPrivateKeyService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.key.service.StandardPrivateKeyService', name, properties=properties)

def CSVRecordLookupService(name: str = 'CSVRecordLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.CSVRecordLookupService', name, properties=properties)

def DistributedMapCacheLookupService(name: str = 'DistributedMapCacheLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.DistributedMapCacheLookupService', name, properties=properties)

def PropertiesFileLookupService(name: str = 'PropertiesFileLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.PropertiesFileLookupService', name, properties=properties)

def ReaderLookup(name: str = 'ReaderLookup', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.ReaderLookup', name, properties=properties)

def RecordSetWriterLookup(name: str = 'RecordSetWriterLookup', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.RecordSetWriterLookup', name, properties=properties)

def RestLookupService(name: str = 'RestLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.RestLookupService', name, properties=properties)

def SimpleCsvFileLookupService(name: str = 'SimpleCsvFileLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.SimpleCsvFileLookupService', name, properties=properties)

def SimpleKeyValueLookupService(name: str = 'SimpleKeyValueLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.SimpleKeyValueLookupService', name, properties=properties)

def XMLFileLookupService(name: str = 'XMLFileLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.XMLFileLookupService', name, properties=properties)

def DatabaseRecordLookupService(name: str = 'DatabaseRecordLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.db.DatabaseRecordLookupService', name, properties=properties)

def SimpleDatabaseLookupService(name: str = 'SimpleDatabaseLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.db.SimpleDatabaseLookupService', name, properties=properties)

def IPLookupService(name: str = 'IPLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.maxmind.IPLookupService', name, properties=properties)

def ScriptedLookupService(name: str = 'ScriptedLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.script.ScriptedLookupService', name, properties=properties)

def SimpleScriptedLookupService(name: str = 'SimpleScriptedLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.lookup.script.SimpleScriptedLookupService', name, properties=properties)

def MongoDBControllerService(name: str = 'MongoDBControllerService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.mongodb.MongoDBControllerService', name, properties=properties)

def MongoDBLookupService(name: str = 'MongoDBLookupService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.mongodb.MongoDBLookupService', name, properties=properties)

def JWTBearerOAuth2AccessTokenProvider(name: str = 'JWTBearerOAuth2AccessTokenProvider', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.oauth2.JWTBearerOAuth2AccessTokenProvider', name, properties=properties)

def StandardOauth2AccessTokenProvider(name: str = 'StandardOauth2AccessTokenProvider', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.oauth2.StandardOauth2AccessTokenProvider', name, properties=properties)

def StandardPGPPrivateKeyService(name: str = 'StandardPGPPrivateKeyService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.pgp.service.standard.StandardPGPPrivateKeyService', name, properties=properties)

def StandardPGPPublicKeyService(name: str = 'StandardPGPPublicKeyService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.pgp.service.standard.StandardPGPPublicKeyService', name, properties=properties)

def AWSCredentialsProviderControllerService(name: str = 'AWSCredentialsProviderControllerService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.processors.aws.credentials.provider.service.AWSCredentialsProviderControllerService', name, properties=properties)

def AwsRdsIamDatabasePasswordProvider(name: str = 'AwsRdsIamDatabasePasswordProvider', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.processors.aws.rds.AwsRdsIamDatabasePasswordProvider', name, properties=properties)

def StandardS3EncryptionService(name: str = 'StandardS3EncryptionService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.processors.aws.s3.encryption.StandardS3EncryptionService', name, properties=properties)

def S3FileResourceService(name: str = 'S3FileResourceService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.processors.aws.s3.service.S3FileResourceService', name, properties=properties)

def GCPCredentialsControllerService(name: str = 'GCPCredentialsControllerService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.processors.gcp.credentials.service.GCPCredentialsControllerService', name, properties=properties)

def GCSFileResourceService(name: str = 'GCSFileResourceService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.processors.gcp.storage.GCSFileResourceService', name, properties=properties)

def StandardProxyConfigurationService(name: str = 'StandardProxyConfigurationService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.proxy.StandardProxyConfigurationService', name, properties=properties)

def ScriptedReader(name: str = 'ScriptedReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.record.script.ScriptedReader', name, properties=properties)

def ScriptedRecordSetWriter(name: str = 'ScriptedRecordSetWriter', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.record.script.ScriptedRecordSetWriter', name, properties=properties)

def EmailRecordSink(name: str = 'EmailRecordSink', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.record.sink.EmailRecordSink', name, properties=properties)

def HttpRecordSink(name: str = 'HttpRecordSink', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.record.sink.HttpRecordSink', name, properties=properties)

def LoggingRecordSink(name: str = 'LoggingRecordSink', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.record.sink.LoggingRecordSink', name, properties=properties)

def DatabaseRecordSink(name: str = 'DatabaseRecordSink', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.record.sink.db.DatabaseRecordSink', name, properties=properties)

def UDPEventRecordSink(name: str = 'UDPEventRecordSink', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.record.sink.event.UDPEventRecordSink', name, properties=properties)

def RecordSinkServiceLookup(name: str = 'RecordSinkServiceLookup', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.record.sink.lookup.RecordSinkServiceLookup', name, properties=properties)

def ScriptedRecordSink(name: str = 'ScriptedRecordSink', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.record.sink.script.ScriptedRecordSink', name, properties=properties)

def RedisConnectionPoolService(name: str = 'RedisConnectionPoolService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.redis.service.RedisConnectionPoolService', name, properties=properties)

def RedisDistributedMapCacheClientService(name: str = 'RedisDistributedMapCacheClientService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.redis.service.RedisDistributedMapCacheClientService', name, properties=properties)

def SimpleRedisDistributedMapCacheClientService(name: str = 'SimpleRedisDistributedMapCacheClientService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.redis.service.SimpleRedisDistributedMapCacheClientService', name, properties=properties)

def SiteToSiteReportingRecordSink(name: str = 'SiteToSiteReportingRecordSink', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.reporting.sink.SiteToSiteReportingRecordSink', name, properties=properties)

def VolatileSchemaCache(name: str = 'VolatileSchemaCache', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.schema.inference.VolatileSchemaCache', name, properties=properties)

def AvroSchemaRegistry(name: str = 'AvroSchemaRegistry', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.schemaregistry.services.AvroSchemaRegistry', name, properties=properties)

def StandardJsonSchemaRegistry(name: str = 'StandardJsonSchemaRegistry', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.schemaregistry.services.StandardJsonSchemaRegistry', name, properties=properties)

def StandardAzureCredentialsControllerService(name: str = 'StandardAzureCredentialsControllerService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.azure.StandardAzureCredentialsControllerService', name, properties=properties)

def AzureCosmosDBClientService(name: str = 'AzureCosmosDBClientService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.azure.cosmos.document.AzureCosmosDBClientService', name, properties=properties)

def StandardKustoIngestService(name: str = 'StandardKustoIngestService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.azure.data.explorer.StandardKustoIngestService', name, properties=properties)

def StandardKustoQueryService(name: str = 'StandardKustoQueryService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.azure.data.explorer.StandardKustoQueryService', name, properties=properties)

def AzureEventHubRecordSink(name: str = 'AzureEventHubRecordSink', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.azure.eventhub.AzureEventHubRecordSink', name, properties=properties)

def ADLSCredentialsControllerService(name: str = 'ADLSCredentialsControllerService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.azure.storage.ADLSCredentialsControllerService', name, properties=properties)

def ADLSCredentialsControllerServiceLookup(name: str = 'ADLSCredentialsControllerServiceLookup', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.azure.storage.ADLSCredentialsControllerServiceLookup', name, properties=properties)

def AzureBlobStorageFileResourceService(name: str = 'AzureBlobStorageFileResourceService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.azure.storage.AzureBlobStorageFileResourceService', name, properties=properties)

def AzureDataLakeStorageFileResourceService(name: str = 'AzureDataLakeStorageFileResourceService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.azure.storage.AzureDataLakeStorageFileResourceService', name, properties=properties)

def AzureStorageCredentialsControllerServiceLookup_v12(name: str = 'AzureStorageCredentialsControllerServiceLookup_v12', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.azure.storage.AzureStorageCredentialsControllerServiceLookup_v12', name, properties=properties)

def AzureStorageCredentialsControllerService_v12(name: str = 'AzureStorageCredentialsControllerService_v12', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.azure.storage.AzureStorageCredentialsControllerService_v12', name, properties=properties)

def StandardDropboxCredentialService(name: str = 'StandardDropboxCredentialService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.dropbox.StandardDropboxCredentialService', name, properties=properties)

def S3IcebergFileIOProvider(name: str = 'S3IcebergFileIOProvider', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.iceberg.aws.S3IcebergFileIOProvider', name, properties=properties)

def ADLSIcebergFileIOProvider(name: str = 'ADLSIcebergFileIOProvider', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.iceberg.azure.ADLSIcebergFileIOProvider', name, properties=properties)

def RESTIcebergCatalog(name: str = 'RESTIcebergCatalog', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.iceberg.catalog.RESTIcebergCatalog', name, properties=properties)

def ParquetIcebergWriter(name: str = 'ParquetIcebergWriter', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.iceberg.parquet.ParquetIcebergWriter', name, properties=properties)

def ProtobufReader(name: str = 'ProtobufReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.protobuf.ProtobufReader', name, properties=properties)

def StandardProtobufReader(name: str = 'StandardProtobufReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.protobuf.StandardProtobufReader', name, properties=properties)

def SlackRecordSink(name: str = 'SlackRecordSink', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.slack.SlackRecordSink', name, properties=properties)

def SmbjClientProviderService(name: str = 'SmbjClientProviderService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.smb.SmbjClientProviderService', name, properties=properties)

def ZendeskRecordSink(name: str = 'ZendeskRecordSink', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.services.zendesk.ZendeskRecordSink', name, properties=properties)

def PEMEncodedSSLContextProvider(name: str = 'PEMEncodedSSLContextProvider', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.ssl.PEMEncodedSSLContextProvider', name, properties=properties)

def StandardRestrictedSSLContextService(name: str = 'StandardRestrictedSSLContextService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.ssl.StandardRestrictedSSLContextService', name, properties=properties)

def StandardSSLContextService(name: str = 'StandardSSLContextService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.ssl.StandardSSLContextService', name, properties=properties)

def Syslog5424Reader(name: str = 'Syslog5424Reader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.syslog.Syslog5424Reader', name, properties=properties)

def SyslogReader(name: str = 'SyslogReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.syslog.SyslogReader', name, properties=properties)

def FreeFormTextRecordSetWriter(name: str = 'FreeFormTextRecordSetWriter', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.text.FreeFormTextRecordSetWriter', name, properties=properties)

def StandardHashiCorpVaultClientService(name: str = 'StandardHashiCorpVaultClientService', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.vault.hashicorp.StandardHashiCorpVaultClientService', name, properties=properties)

def StandardWebClientServiceProvider(name: str = 'StandardWebClientServiceProvider', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.web.client.provider.service.StandardWebClientServiceProvider', name, properties=properties)

def JettyWebSocketClient(name: str = 'JettyWebSocketClient', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.websocket.jetty.JettyWebSocketClient', name, properties=properties)

def JettyWebSocketServer(name: str = 'JettyWebSocketServer', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.websocket.jetty.JettyWebSocketServer', name, properties=properties)

def WindowsEventLogReader(name: str = 'WindowsEventLogReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.windowsevent.WindowsEventLogReader', name, properties=properties)

def XMLReader(name: str = 'XMLReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.xml.XMLReader', name, properties=properties)

def XMLRecordSetWriter(name: str = 'XMLRecordSetWriter', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.xml.XMLRecordSetWriter', name, properties=properties)

def YamlTreeReader(name: str = 'YamlTreeReader', properties: Optional[Dict[str, Any]] = None) -> ControllerService:
    return _service('org.apache.nifi.yaml.YamlTreeReader', name, properties=properties)

ALL = [
    ApicurioSchemaRegistry,
    AvroReader,
    AvroRecordSetWriter,
    AmazonGlueEncodedSchemaReferenceReader,
    AmazonGlueSchemaRegistry,
    DeveloperBoxClientService,
    JsonConfigBasedBoxClientService,
    CEFReader,
    ConfluentEncodedSchemaReferenceReader,
    ConfluentEncodedSchemaReferenceWriter,
    ConfluentProtobufMessageNameResolver,
    ConfluentSchemaRegistry,
    StandardAsanaClientProviderService,
    CSVReader,
    CSVRecordSetWriter,
    StandardDatabaseDialectService,
    DatabaseTableSchemaRegistry,
    DBCPConnectionPool,
    DBCPConnectionPoolLookup,
    HikariCPConnectionPool,
    MapCacheClientService,
    SetCacheClientService,
    SetCacheServer,
    MapCacheServer,
    ElasticSearchClientServiceImpl,
    ElasticSearchLookupService,
    ElasticSearchStringLookupService,
    ExcelReader,
    StandardFileResourceService,
    GrokReader,
    HazelcastMapCacheClient,
    EmbeddedHazelcastCacheManager,
    ExternalHazelcastCacheManager,
    StandardHttpContextMap,
    JMSConnectionFactoryProvider,
    JndiJmsConnectionFactoryProvider,
    JsonPathReader,
    JsonRecordSetWriter,
    JsonTreeReader,
    Kafka3ConnectionService,
    AmazonMSKConnectionService,
    KerberosKeytabUserService,
    KerberosPasswordUserService,
    KerberosTicketCacheUserService,
    StandardPrivateKeyService,
    CSVRecordLookupService,
    DistributedMapCacheLookupService,
    PropertiesFileLookupService,
    ReaderLookup,
    RecordSetWriterLookup,
    RestLookupService,
    SimpleCsvFileLookupService,
    SimpleKeyValueLookupService,
    XMLFileLookupService,
    DatabaseRecordLookupService,
    SimpleDatabaseLookupService,
    IPLookupService,
    ScriptedLookupService,
    SimpleScriptedLookupService,
    MongoDBControllerService,
    MongoDBLookupService,
    JWTBearerOAuth2AccessTokenProvider,
    StandardOauth2AccessTokenProvider,
    StandardPGPPrivateKeyService,
    StandardPGPPublicKeyService,
    AWSCredentialsProviderControllerService,
    AwsRdsIamDatabasePasswordProvider,
    StandardS3EncryptionService,
    S3FileResourceService,
    GCPCredentialsControllerService,
    GCSFileResourceService,
    StandardProxyConfigurationService,
    ScriptedReader,
    ScriptedRecordSetWriter,
    EmailRecordSink,
    HttpRecordSink,
    LoggingRecordSink,
    DatabaseRecordSink,
    UDPEventRecordSink,
    RecordSinkServiceLookup,
    ScriptedRecordSink,
    RedisConnectionPoolService,
    RedisDistributedMapCacheClientService,
    SimpleRedisDistributedMapCacheClientService,
    SiteToSiteReportingRecordSink,
    VolatileSchemaCache,
    AvroSchemaRegistry,
    StandardJsonSchemaRegistry,
    StandardAzureCredentialsControllerService,
    AzureCosmosDBClientService,
    StandardKustoIngestService,
    StandardKustoQueryService,
    AzureEventHubRecordSink,
    ADLSCredentialsControllerService,
    ADLSCredentialsControllerServiceLookup,
    AzureBlobStorageFileResourceService,
    AzureDataLakeStorageFileResourceService,
    AzureStorageCredentialsControllerServiceLookup_v12,
    AzureStorageCredentialsControllerService_v12,
    StandardDropboxCredentialService,
    S3IcebergFileIOProvider,
    ADLSIcebergFileIOProvider,
    RESTIcebergCatalog,
    ParquetIcebergWriter,
    ProtobufReader,
    StandardProtobufReader,
    SlackRecordSink,
    SmbjClientProviderService,
    ZendeskRecordSink,
    PEMEncodedSSLContextProvider,
    StandardRestrictedSSLContextService,
    StandardSSLContextService,
    Syslog5424Reader,
    SyslogReader,
    FreeFormTextRecordSetWriter,
    StandardHashiCorpVaultClientService,
    StandardWebClientServiceProvider,
    JettyWebSocketClient,
    JettyWebSocketServer,
    WindowsEventLogReader,
    XMLReader,
    XMLRecordSetWriter,
    YamlTreeReader,
]

TYPES = [
    'org.apache.nifi.apicurio.schemaregistry.ApicurioSchemaRegistry',
    'org.apache.nifi.avro.AvroReader',
    'org.apache.nifi.avro.AvroRecordSetWriter',
    'org.apache.nifi.aws.schemaregistry.AmazonGlueEncodedSchemaReferenceReader',
    'org.apache.nifi.aws.schemaregistry.AmazonGlueSchemaRegistry',
    'org.apache.nifi.box.controllerservices.DeveloperBoxClientService',
    'org.apache.nifi.box.controllerservices.JsonConfigBasedBoxClientService',
    'org.apache.nifi.cef.CEFReader',
    'org.apache.nifi.confluent.schemaregistry.ConfluentEncodedSchemaReferenceReader',
    'org.apache.nifi.confluent.schemaregistry.ConfluentEncodedSchemaReferenceWriter',
    'org.apache.nifi.confluent.schemaregistry.ConfluentProtobufMessageNameResolver',
    'org.apache.nifi.confluent.schemaregistry.ConfluentSchemaRegistry',
    'org.apache.nifi.controller.asana.StandardAsanaClientProviderService',
    'org.apache.nifi.csv.CSVReader',
    'org.apache.nifi.csv.CSVRecordSetWriter',
    'org.apache.nifi.database.dialect.service.StandardDatabaseDialectService',
    'org.apache.nifi.db.schemaregistry.DatabaseTableSchemaRegistry',
    'org.apache.nifi.dbcp.DBCPConnectionPool',
    'org.apache.nifi.dbcp.DBCPConnectionPoolLookup',
    'org.apache.nifi.dbcp.HikariCPConnectionPool',
    'org.apache.nifi.distributed.cache.client.MapCacheClientService',
    'org.apache.nifi.distributed.cache.client.SetCacheClientService',
    'org.apache.nifi.distributed.cache.server.SetCacheServer',
    'org.apache.nifi.distributed.cache.server.map.MapCacheServer',
    'org.apache.nifi.elasticsearch.ElasticSearchClientServiceImpl',
    'org.apache.nifi.elasticsearch.ElasticSearchLookupService',
    'org.apache.nifi.elasticsearch.ElasticSearchStringLookupService',
    'org.apache.nifi.excel.ExcelReader',
    'org.apache.nifi.fileresource.service.StandardFileResourceService',
    'org.apache.nifi.grok.GrokReader',
    'org.apache.nifi.hazelcast.services.cacheclient.HazelcastMapCacheClient',
    'org.apache.nifi.hazelcast.services.cachemanager.EmbeddedHazelcastCacheManager',
    'org.apache.nifi.hazelcast.services.cachemanager.ExternalHazelcastCacheManager',
    'org.apache.nifi.http.StandardHttpContextMap',
    'org.apache.nifi.jms.cf.JMSConnectionFactoryProvider',
    'org.apache.nifi.jms.cf.JndiJmsConnectionFactoryProvider',
    'org.apache.nifi.json.JsonPathReader',
    'org.apache.nifi.json.JsonRecordSetWriter',
    'org.apache.nifi.json.JsonTreeReader',
    'org.apache.nifi.kafka.service.Kafka3ConnectionService',
    'org.apache.nifi.kafka.service.aws.AmazonMSKConnectionService',
    'org.apache.nifi.kerberos.KerberosKeytabUserService',
    'org.apache.nifi.kerberos.KerberosPasswordUserService',
    'org.apache.nifi.kerberos.KerberosTicketCacheUserService',
    'org.apache.nifi.key.service.StandardPrivateKeyService',
    'org.apache.nifi.lookup.CSVRecordLookupService',
    'org.apache.nifi.lookup.DistributedMapCacheLookupService',
    'org.apache.nifi.lookup.PropertiesFileLookupService',
    'org.apache.nifi.lookup.ReaderLookup',
    'org.apache.nifi.lookup.RecordSetWriterLookup',
    'org.apache.nifi.lookup.RestLookupService',
    'org.apache.nifi.lookup.SimpleCsvFileLookupService',
    'org.apache.nifi.lookup.SimpleKeyValueLookupService',
    'org.apache.nifi.lookup.XMLFileLookupService',
    'org.apache.nifi.lookup.db.DatabaseRecordLookupService',
    'org.apache.nifi.lookup.db.SimpleDatabaseLookupService',
    'org.apache.nifi.lookup.maxmind.IPLookupService',
    'org.apache.nifi.lookup.script.ScriptedLookupService',
    'org.apache.nifi.lookup.script.SimpleScriptedLookupService',
    'org.apache.nifi.mongodb.MongoDBControllerService',
    'org.apache.nifi.mongodb.MongoDBLookupService',
    'org.apache.nifi.oauth2.JWTBearerOAuth2AccessTokenProvider',
    'org.apache.nifi.oauth2.StandardOauth2AccessTokenProvider',
    'org.apache.nifi.pgp.service.standard.StandardPGPPrivateKeyService',
    'org.apache.nifi.pgp.service.standard.StandardPGPPublicKeyService',
    'org.apache.nifi.processors.aws.credentials.provider.service.AWSCredentialsProviderControllerService',
    'org.apache.nifi.processors.aws.rds.AwsRdsIamDatabasePasswordProvider',
    'org.apache.nifi.processors.aws.s3.encryption.StandardS3EncryptionService',
    'org.apache.nifi.processors.aws.s3.service.S3FileResourceService',
    'org.apache.nifi.processors.gcp.credentials.service.GCPCredentialsControllerService',
    'org.apache.nifi.processors.gcp.storage.GCSFileResourceService',
    'org.apache.nifi.proxy.StandardProxyConfigurationService',
    'org.apache.nifi.record.script.ScriptedReader',
    'org.apache.nifi.record.script.ScriptedRecordSetWriter',
    'org.apache.nifi.record.sink.EmailRecordSink',
    'org.apache.nifi.record.sink.HttpRecordSink',
    'org.apache.nifi.record.sink.LoggingRecordSink',
    'org.apache.nifi.record.sink.db.DatabaseRecordSink',
    'org.apache.nifi.record.sink.event.UDPEventRecordSink',
    'org.apache.nifi.record.sink.lookup.RecordSinkServiceLookup',
    'org.apache.nifi.record.sink.script.ScriptedRecordSink',
    'org.apache.nifi.redis.service.RedisConnectionPoolService',
    'org.apache.nifi.redis.service.RedisDistributedMapCacheClientService',
    'org.apache.nifi.redis.service.SimpleRedisDistributedMapCacheClientService',
    'org.apache.nifi.reporting.sink.SiteToSiteReportingRecordSink',
    'org.apache.nifi.schema.inference.VolatileSchemaCache',
    'org.apache.nifi.schemaregistry.services.AvroSchemaRegistry',
    'org.apache.nifi.schemaregistry.services.StandardJsonSchemaRegistry',
    'org.apache.nifi.services.azure.StandardAzureCredentialsControllerService',
    'org.apache.nifi.services.azure.cosmos.document.AzureCosmosDBClientService',
    'org.apache.nifi.services.azure.data.explorer.StandardKustoIngestService',
    'org.apache.nifi.services.azure.data.explorer.StandardKustoQueryService',
    'org.apache.nifi.services.azure.eventhub.AzureEventHubRecordSink',
    'org.apache.nifi.services.azure.storage.ADLSCredentialsControllerService',
    'org.apache.nifi.services.azure.storage.ADLSCredentialsControllerServiceLookup',
    'org.apache.nifi.services.azure.storage.AzureBlobStorageFileResourceService',
    'org.apache.nifi.services.azure.storage.AzureDataLakeStorageFileResourceService',
    'org.apache.nifi.services.azure.storage.AzureStorageCredentialsControllerServiceLookup_v12',
    'org.apache.nifi.services.azure.storage.AzureStorageCredentialsControllerService_v12',
    'org.apache.nifi.services.dropbox.StandardDropboxCredentialService',
    'org.apache.nifi.services.iceberg.aws.S3IcebergFileIOProvider',
    'org.apache.nifi.services.iceberg.azure.ADLSIcebergFileIOProvider',
    'org.apache.nifi.services.iceberg.catalog.RESTIcebergCatalog',
    'org.apache.nifi.services.iceberg.parquet.ParquetIcebergWriter',
    'org.apache.nifi.services.protobuf.ProtobufReader',
    'org.apache.nifi.services.protobuf.StandardProtobufReader',
    'org.apache.nifi.services.slack.SlackRecordSink',
    'org.apache.nifi.services.smb.SmbjClientProviderService',
    'org.apache.nifi.services.zendesk.ZendeskRecordSink',
    'org.apache.nifi.ssl.PEMEncodedSSLContextProvider',
    'org.apache.nifi.ssl.StandardRestrictedSSLContextService',
    'org.apache.nifi.ssl.StandardSSLContextService',
    'org.apache.nifi.syslog.Syslog5424Reader',
    'org.apache.nifi.syslog.SyslogReader',
    'org.apache.nifi.text.FreeFormTextRecordSetWriter',
    'org.apache.nifi.vault.hashicorp.StandardHashiCorpVaultClientService',
    'org.apache.nifi.web.client.provider.service.StandardWebClientServiceProvider',
    'org.apache.nifi.websocket.jetty.JettyWebSocketClient',
    'org.apache.nifi.websocket.jetty.JettyWebSocketServer',
    'org.apache.nifi.windowsevent.WindowsEventLogReader',
    'org.apache.nifi.xml.XMLReader',
    'org.apache.nifi.xml.XMLRecordSetWriter',
    'org.apache.nifi.yaml.YamlTreeReader',
]

RESTRICTED = {
    'org.apache.nifi.dbcp.DBCPConnectionPool',
    'org.apache.nifi.dbcp.HikariCPConnectionPool',
    'org.apache.nifi.fileresource.service.StandardFileResourceService',
    'org.apache.nifi.grok.GrokReader',
    'org.apache.nifi.jms.cf.JMSConnectionFactoryProvider',
    'org.apache.nifi.kerberos.KerberosKeytabUserService',
    'org.apache.nifi.kerberos.KerberosTicketCacheUserService',
    'org.apache.nifi.lookup.CSVRecordLookupService',
    'org.apache.nifi.lookup.PropertiesFileLookupService',
    'org.apache.nifi.lookup.SimpleCsvFileLookupService',
    'org.apache.nifi.lookup.XMLFileLookupService',
    'org.apache.nifi.lookup.script.ScriptedLookupService',
    'org.apache.nifi.lookup.script.SimpleScriptedLookupService',
    'org.apache.nifi.processors.aws.credentials.provider.service.AWSCredentialsProviderControllerService',
    'org.apache.nifi.processors.gcp.credentials.service.GCPCredentialsControllerService',
    'org.apache.nifi.record.script.ScriptedReader',
    'org.apache.nifi.record.script.ScriptedRecordSetWriter',
    'org.apache.nifi.record.sink.script.ScriptedRecordSink',
}

DEPRECATED = {
    'org.apache.nifi.controller.asana.StandardAsanaClientProviderService',
    'org.apache.nifi.ssl.StandardRestrictedSSLContextService',
}
