"""Running a sweep: repro files, resumable results, replay, and the report.

A sweep streams one JSON record per case to ``<out>/results.jsonl`` and flushes
after each one, so a multi-hour run survives a kill and ``--resume`` picks it
up. Each distinct root-cause signature writes up to
``max_repros_per_signature`` standalone repro directories — a runnable flow
module, the case spec, and the findings — so a bug can be handed to `niflow
validate` / `push` directly, or replayed with ``niflow fuzz --replay <id>``.
"""
from __future__ import annotations

import json
import logging
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Tuple

from niflow.fuzz.cases import (
    DEFAULT_OUT_DIR,
    KINDS,
    SANDBOX_PREFIX,
    NIFI_REJECTED,
    NIFLOW_BUG,
    PASSED,
    Case,
    _catalog,
    generate_cases,
)
from niflow.fuzz.checks import (
    CaseResult,
    Finding,
    _exception_finding,
    check_live_roundtrip,
    check_live_validate,
    check_offline,
)
# =============================================================================
# repro emission
# =============================================================================


_REPRO_TEMPLATE = '''"""niflow fuzz repro — case {case_id} ({kind}).

Generated by `niflow fuzz`. This module is a normal niflow flow file: it
exposes a top-level `flow`, so every niflow command works on it.

    niflow validate {path}
    niflow plan {path}
    niflow push {path}
    niflow fuzz --replay {case_id}

What failed:
{failures}
"""
from niflow.fuzz import build_case_flow

KIND = {kind!r}
SPEC = {spec}

flow = build_case_flow(KIND, SPEC)
'''


def write_repro(result: CaseResult, out_dir: Path) -> Path:
    """Write a minimal, standalone, runnable reproduction of a failing case."""
    directory = Path(out_dir) / "repro" / result.case.case_id
    directory.mkdir(parents=True, exist_ok=True)
    flow_path = directory / "flow.py"
    failures = "\n".join(
        f"  * [{f.check}] {f.message}" for f in result.findings) or "  (none)"
    flow_path.write_text(_REPRO_TEMPLATE.format(
        case_id=result.case.case_id,
        kind=result.case.kind,
        spec=_pretty_spec(result.case.spec),
        path=flow_path,
        failures=failures,
    ), encoding="utf-8")
    (directory / "case.json").write_text(
        json.dumps(result.to_dict(), indent=2, ensure_ascii=False), encoding="utf-8")

    details = "\n\n".join(
        f"### {f.check} [{f.classification}] {f.signature}\n{f.message}\n\n{f.detail}"
        for f in result.findings)
    (directory / "findings.txt").write_text(details, encoding="utf-8")

    # A best-effort expanded form: the same flow written out as plain niflow
    # code, for hand-editing. Skipped when the emitter itself is the casualty.
    try:
        from niflow.formats import to_python

        (directory / "flow_expanded.py").write_text(
            to_python(result.case.build(),
                      module_docstring=f"Expanded repro for fuzz case {result.case.case_id}."),
            encoding="utf-8")
    except Exception:
        pass
    return flow_path


def _pretty_spec(spec: Dict[str, Any]) -> str:
    return json.dumps(spec, indent=4, ensure_ascii=False).replace(": true", ": True") \
        .replace(": false", ": False").replace(": null", ": None")


# =============================================================================
# sweep
# =============================================================================


def cleanup_sandboxes(client: Any, prefix: str = SANDBOX_PREFIX) -> int:
    """Delete every leftover fuzz sandbox on the target; returns how many went.

    A long live sweep must not litter someone's canvas: NiFi keeps the
    half-created group behind when a push fails mid-import, and a delete can
    409 while the server is still settling — so this runs a few passes and
    never raises.
    """
    removed = 0
    for _ in range(3):
        try:
            stale = [component["id"] for _, component in client.walk_groups()
                     if str(component.get("name") or "").startswith(prefix)]
        except Exception:  # pragma: no cover - inventory is a cheap GET
            return removed
        if not stale:
            break
        progressed = False
        for pg_id in stale:
            try:
                client.delete_group(pg_id)
            except Exception:
                continue
            removed += 1
            progressed = True
        if not progressed:
            break
    return removed


@dataclass
class SweepConfig:
    tier: int = 1
    count: int = 0
    seed: int = 0
    kinds: Tuple[str, ...] = KINDS
    type_pattern: Optional[str] = None
    out_dir: Path = DEFAULT_OUT_DIR
    resume: bool = False
    target_majors: Tuple[int, ...] = (1,)
    max_repros_per_signature: int = 3
    max_failures: int = 0
    keep_sandboxes: bool = False
    quiet: bool = False

    def to_dict(self) -> Dict[str, Any]:
        data = dict(self.__dict__)
        data["out_dir"] = str(self.out_dir)
        data["kinds"] = list(self.kinds)
        data["target_majors"] = list(self.target_majors)
        return data


@dataclass
class Report:
    config: SweepConfig
    results: List[CaseResult] = field(default_factory=list)
    skipped: int = 0
    elapsed: float = 0.0
    stopped_early: bool = False
    sandboxes_removed: int = 0

    @property
    def counts(self) -> Dict[str, int]:
        counts = {PASSED: 0, NIFLOW_BUG: 0, NIFI_REJECTED: 0}
        for result in self.results:
            counts[result.status] = counts.get(result.status, 0) + 1
        return counts

    def by_signature(self, classification: str = NIFLOW_BUG) -> Dict[str, List[CaseResult]]:
        grouped: Dict[str, List[CaseResult]] = {}
        for result in self.results:
            for finding in result.findings:
                if finding.classification != classification:
                    continue
                grouped.setdefault(finding.signature, []).append(result)
        return dict(sorted(grouped.items(), key=lambda kv: -len(kv[1])))


def run_case(case: Case, config: SweepConfig, client: Any = None) -> CaseResult:
    """Run one case at the configured tier."""
    if config.tier >= 3 and client is not None:
        return check_live_roundtrip(case, client)
    if config.tier >= 2 and client is not None:
        return check_live_validate(case, client)
    return check_offline(case, target_majors=config.target_majors)


def _load_previous(path: Path) -> Dict[str, Dict[str, Any]]:
    previous: Dict[str, Dict[str, Any]] = {}
    if not path.exists():
        return previous
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError:  # truncated final line from a hard kill
            continue
        previous[record["case_id"]] = record
    return previous


def _result_from_record(record: Dict[str, Any]) -> CaseResult:
    case = Case(record["kind"], record["spec"])
    result = CaseResult(case, status=record.get("status", PASSED),
                        elapsed=record.get("elapsed", 0.0),
                        observations=record.get("observations", []))
    result.findings = [Finding(**f) for f in record.get("findings", [])]
    return result


def sweep(config: SweepConfig, client: Any = None,
          progress: Optional[Callable[[int, int, CaseResult], None]] = None) -> Report:
    """Run a whole sweep, streaming results to disk so it survives a restart."""
    out_dir = Path(config.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    results_path = out_dir / "results.jsonl"

    previous = _load_previous(results_path) if config.resume else {}
    if not config.resume and results_path.exists():
        results_path.unlink()
    (out_dir / "run.json").write_text(json.dumps({
        "config": config.to_dict(),
        "catalog": getattr(_catalog(), "CATALOG_META", {}),
        "started": time.strftime("%Y-%m-%d %H:%M:%S"),
    }, indent=2), encoding="utf-8")

    cases = generate_cases(seed=config.seed, kinds=config.kinds,
                           type_pattern=config.type_pattern, count=config.count)
    report = Report(config=config)
    repro_counts: Dict[str, int] = {}
    started = time.perf_counter()

    # The emitters log a warning per cross-version property drop; at this
    # volume that is pure noise (the drops are recorded as observations).
    logger = logging.getLogger("niflow")
    previous_level = logger.level
    logger.setLevel(logging.ERROR)
    try:
        with results_path.open("a", encoding="utf-8") as handle:
            for index, case in enumerate(cases, 1):
                record = previous.get(case.case_id)
                if record is not None:
                    result = _result_from_record(record)
                    report.results.append(result)
                    report.skipped += 1
                    continue
                try:
                    result = run_case(case, config, client)
                except Exception as exc:  # harness bug — record, never abort
                    result = CaseResult(case)
                    result.add(_exception_finding("harness", exc))
                report.results.append(result)
                handle.write(json.dumps(result.to_dict(), ensure_ascii=False) + "\n")
                handle.flush()

                for finding in result.findings:
                    if finding.classification != NIFLOW_BUG:
                        continue
                    seen = repro_counts.get(finding.signature, 0)
                    if seen < config.max_repros_per_signature:
                        repro_counts[finding.signature] = seen + 1
                        write_repro(result, out_dir)
                    break
                if progress is not None:
                    progress(index, len(cases), result)
                if config.max_failures and report.counts[NIFLOW_BUG] >= config.max_failures:
                    report.stopped_early = True
                    break
    finally:
        logger.setLevel(previous_level)

    report.elapsed = time.perf_counter() - started
    if client is not None and not config.keep_sandboxes:
        report.sandboxes_removed = cleanup_sandboxes(client)
    (out_dir / "summary.txt").write_text(format_report(report), encoding="utf-8")
    return report


def replay(case_id: str, config: SweepConfig, client: Any = None) -> CaseResult:
    """Re-run exactly one case, by id — the narrowing loop after a big sweep."""
    case = find_case(case_id, config)
    if case is None:
        raise LookupError(
            f"case {case_id!r} not found — it is not in {config.out_dir}/results.jsonl "
            f"and the current --seed/--kinds/--types do not generate it")
    return run_case(case, config, client)


def find_case(case_id: str, config: SweepConfig) -> Optional[Case]:
    """Locate a case by id: saved repro first, then the run log, then regenerate."""
    repro = Path(config.out_dir) / "repro" / case_id / "case.json"
    if repro.exists():
        record = json.loads(repro.read_text(encoding="utf-8"))
        return Case(record["kind"], record["spec"])
    for record in _load_previous(Path(config.out_dir) / "results.jsonl").values():
        if record["case_id"] == case_id:
            return Case(record["kind"], record["spec"])
    for case in generate_cases(seed=config.seed, kinds=config.kinds,
                               type_pattern=config.type_pattern):
        if case.case_id == case_id:
            return case
    return None


# =============================================================================
# reporting
# =============================================================================


def format_report(report: Report) -> str:
    """The end-of-sweep summary: counts, then findings grouped by root cause."""
    counts = report.counts
    total = len(report.results)
    lines = [
        f"niflow fuzz — tier {report.config.tier}, seed {report.config.seed}, "
        f"{total} case(s) in {report.elapsed:.1f}s"
        + (f" ({report.skipped} resumed)" if report.skipped else ""),
        "",
        f"  passed         {counts[PASSED]:>6}",
        f"  niflow bug     {counts[NIFLOW_BUG]:>6}",
        f"  NiFi rejected  {counts[NIFI_REJECTED]:>6}",
    ]
    if report.stopped_early:
        lines.append("  (stopped early: --max-failures reached)")
    if report.sandboxes_removed:
        lines.append(f"  ({report.sandboxes_removed} leftover sandbox group(s) "
                     "cleaned up)")

    for classification, title in ((NIFLOW_BUG, "niflow bugs"),
                                  (NIFI_REJECTED, "NiFi rejections")):
        grouped = report.by_signature(classification)
        if not grouped:
            continue
        lines += ["", f"{title} — {len(grouped)} distinct signature(s):"]
        for signature, results in grouped.items():
            first = results[0]
            finding = next(f for f in first.findings if f.signature == signature)
            lines += [
                "",
                f"  [{signature}]  ×{len(results)}",
                f"    {finding.message}",
                f"    first case: {first.case.case_id}  ({_spec_summary(first.case)})",
                f"    replay:     niflow fuzz --replay {first.case.case_id}",
                f"    repro:      {Path(report.config.out_dir) / 'repro' / first.case.case_id / 'flow.py'}",
            ]

    disagreements = [o for result in report.results for o in result.observations
                     if o.get("kind") == "validate_disagreement"]
    if disagreements:
        static_only = sum(1 for o in disagreements if o["direction"] == "static_only")
        lines += [
            "",
            f"validate disagreements not blamed on niflow ({len(disagreements)}):",
            f"  {len(disagreements) - static_only} the server flags and niflow does "
            "not (required/allowable rules differ per NiFi line, or the check is "
            "outside what validate claims)",
        ]
        if static_only:
            lines.append(
                f"  {static_only} niflow flags and the server does not — the catalog "
                "is from the other NiFi line; re-run with a matching catalog "
                "(`make catalog` / `make catalog-v1`) to judge these")

    untranslatable = sorted({
        observation["type"]
        for result in report.results for observation in result.observations
        if observation.get("kind") == "no_cross_version_data"
    })
    if untranslatable:
        # "No 1.x data" has two very different causes and the sweep used to
        # report them as one number. A type that does not EXIST on 1.x has
        # nothing to translate and is not a gap — niflow already refuses it with
        # a "type does not exist on NiFi 1.x" warning. A type that exists there
        # and still has no data is the real hole.
        from niflow.compat import type_missing_on

        absent = [t for t in untranslatable if type_missing_on(t, 1)]
        holes = [t for t in untranslatable if t not in set(absent)]
        if holes:
            lines += [
                "",
                f"types with NO 1.x compatibility data ({len(holes)}) — a "
                "renamed property on these is emitted under its 2.x key and lands on a "
                "1.x server as an inert dynamic property:",
                "  " + ", ".join(t.rsplit(".", 1)[-1] for t in holes[:20])
                + (" …" if len(holes) > 20 else ""),
            ]
        if absent:
            lines += [
                "",
                f"types that do not exist on 1.x ({len(absent)}) — nothing to "
                "translate; a flow using these cannot be pushed to a 1.x server "
                "at all (`niflow validate --target-version 1.x` says so):",
                "  " + ", ".join(t.rsplit(".", 1)[-1] for t in absent[:20])
                + (" …" if len(absent) > 20 else ""),
            ]

    drops = _drop_summary(report)
    if drops:
        lines += ["", f"cross-version property drops (informational, {len(drops)} type(s)):"]
        for type_str, keys in list(drops.items())[:15]:
            lines.append(f"  {type_str}: {', '.join(sorted(keys)[:6])}"
                         + (" …" if len(keys) > 6 else ""))
        if len(drops) > 15:
            lines.append(f"  … and {len(drops) - 15} more type(s)")
    return "\n".join(lines)


def _spec_summary(case: Case) -> str:
    spec = case.spec
    parts = [f"{key}={_short(value)}" for key, value in sorted(spec.items())
             if key != "properties"]
    if "properties" in spec:
        parts.append(f"props={len(spec['properties'])}")
    return " ".join(parts)


def _short(value: Any) -> str:
    text = str(value)
    return text.rsplit(".", 1)[-1] if "." in text and " " not in text else text


def _drop_summary(report: Report) -> Dict[str, set]:
    drops: Dict[str, set] = {}
    for result in report.results:
        for observation in result.observations:
            if observation.get("kind") != "cross_version_drop":
                continue
            drops.setdefault(observation["type"], set()).update(observation["properties"])
    return dict(sorted(drops.items()))
