"""AUTO-GENERATED by ``python -m niflow.codegen`` — do not edit by hand.

Exhaustive catalog of processor types reported by the NiFi instance this was
generated against. Each factory is a thin shell over the type string; for
sensible defaults prefer the curated factories in :mod:`niflow.processors.standard`.

Regenerate after upgrading NiFi or installing new NARs::

    python -m niflow.codegen
"""
from __future__ import annotations

from typing import Any, Dict, Optional

from niflow.processors.standard import _processor
from niflow.core import Processor

def ConsumeAMQP(name: str = 'ConsumeAMQP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.amqp.processors.ConsumeAMQP', name, properties=properties, **settings)

def PublishAMQP(name: str = 'PublishAMQP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.amqp.processors.PublishAMQP', name, properties=properties, **settings)

def CaptureChangeMySQL(name: str = 'CaptureChangeMySQL', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.cdc.mysql.processors.CaptureChangeMySQL', name, properties=properties, **settings)

def ConsumeJMS(name: str = 'ConsumeJMS', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.jms.processors.ConsumeJMS', name, properties=properties, **settings)

def PublishJMS(name: str = 'PublishJMS', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.jms.processors.PublishJMS', name, properties=properties, **settings)

def ConsumeKafka(name: str = 'ConsumeKafka', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.kafka.processors.ConsumeKafka', name, properties=properties, **settings)

def PublishKafka(name: str = 'PublishKafka', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.kafka.processors.PublishKafka', name, properties=properties, **settings)

def GeoEnrichIP(name: str = 'GeoEnrichIP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.GeoEnrichIP', name, properties=properties, **settings)

def GeoEnrichIPRecord(name: str = 'GeoEnrichIPRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.GeoEnrichIPRecord', name, properties=properties, **settings)

def ISPEnrichIP(name: str = 'ISPEnrichIP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.ISPEnrichIP', name, properties=properties, **settings)

def QueryAirtableTable(name: str = 'QueryAirtableTable', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.airtable.QueryAirtableTable', name, properties=properties, **settings)

def GetAsanaObject(name: str = 'GetAsanaObject', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.asana.GetAsanaObject', name, properties=properties, **settings)

def UpdateAttribute(name: str = 'UpdateAttribute', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.attributes.UpdateAttribute', name, properties=properties, **settings)

def ExtractAvroMetadata(name: str = 'ExtractAvroMetadata', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.avro.ExtractAvroMetadata', name, properties=properties, **settings)

def SplitAvro(name: str = 'SplitAvro', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.avro.SplitAvro', name, properties=properties, **settings)

def PutCloudWatchMetric(name: str = 'PutCloudWatchMetric', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.cloudwatch.PutCloudWatchMetric', name, properties=properties, **settings)

def DeleteDynamoDB(name: str = 'DeleteDynamoDB', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.dynamodb.DeleteDynamoDB', name, properties=properties, **settings)

def GetDynamoDB(name: str = 'GetDynamoDB', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.dynamodb.GetDynamoDB', name, properties=properties, **settings)

def PutDynamoDB(name: str = 'PutDynamoDB', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.dynamodb.PutDynamoDB', name, properties=properties, **settings)

def PutDynamoDBRecord(name: str = 'PutDynamoDBRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.dynamodb.PutDynamoDBRecord', name, properties=properties, **settings)

def ConsumeKinesis(name: str = 'ConsumeKinesis', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.kinesis.ConsumeKinesis', name, properties=properties, **settings)

def PutKinesisFirehose(name: str = 'PutKinesisFirehose', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.kinesis.firehose.PutKinesisFirehose', name, properties=properties, **settings)

def ConsumeKinesisStream(name: str = 'ConsumeKinesisStream', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.kinesis.stream.ConsumeKinesisStream', name, properties=properties, **settings)

def PutKinesisStream(name: str = 'PutKinesisStream', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.kinesis.stream.PutKinesisStream', name, properties=properties, **settings)

def PutLambda(name: str = 'PutLambda', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.lambda.PutLambda', name, properties=properties, **settings)

def GetAwsPollyJobStatus(name: str = 'GetAwsPollyJobStatus', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.ml.polly.GetAwsPollyJobStatus', name, properties=properties, **settings)

def StartAwsPollyJob(name: str = 'StartAwsPollyJob', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.ml.polly.StartAwsPollyJob', name, properties=properties, **settings)

def GetAwsTextractJobStatus(name: str = 'GetAwsTextractJobStatus', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.ml.textract.GetAwsTextractJobStatus', name, properties=properties, **settings)

def StartAwsTextractJob(name: str = 'StartAwsTextractJob', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.ml.textract.StartAwsTextractJob', name, properties=properties, **settings)

def GetAwsTranscribeJobStatus(name: str = 'GetAwsTranscribeJobStatus', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.ml.transcribe.GetAwsTranscribeJobStatus', name, properties=properties, **settings)

def StartAwsTranscribeJob(name: str = 'StartAwsTranscribeJob', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.ml.transcribe.StartAwsTranscribeJob', name, properties=properties, **settings)

def GetAwsTranslateJobStatus(name: str = 'GetAwsTranslateJobStatus', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.ml.translate.GetAwsTranslateJobStatus', name, properties=properties, **settings)

def StartAwsTranslateJob(name: str = 'StartAwsTranslateJob', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.ml.translate.StartAwsTranslateJob', name, properties=properties, **settings)

def CopyS3Object(name: str = 'CopyS3Object', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.s3.CopyS3Object', name, properties=properties, **settings)

def DeleteS3Object(name: str = 'DeleteS3Object', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.s3.DeleteS3Object', name, properties=properties, **settings)

def FetchS3Object(name: str = 'FetchS3Object', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.s3.FetchS3Object', name, properties=properties, **settings)

def GetS3ObjectMetadata(name: str = 'GetS3ObjectMetadata', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.s3.GetS3ObjectMetadata', name, properties=properties, **settings)

def GetS3ObjectTags(name: str = 'GetS3ObjectTags', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.s3.GetS3ObjectTags', name, properties=properties, **settings)

def ListS3(name: str = 'ListS3', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.s3.ListS3', name, properties=properties, **settings)

def PutS3Object(name: str = 'PutS3Object', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.s3.PutS3Object', name, properties=properties, **settings)

def TagS3Object(name: str = 'TagS3Object', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.s3.TagS3Object', name, properties=properties, **settings)

def PutSNS(name: str = 'PutSNS', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.sns.PutSNS', name, properties=properties, **settings)

def DeleteSQS(name: str = 'DeleteSQS', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.sqs.DeleteSQS', name, properties=properties, **settings)

def GetSQS(name: str = 'GetSQS', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.sqs.GetSQS', name, properties=properties, **settings)

def PutSQS(name: str = 'PutSQS', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.aws.sqs.PutSQS', name, properties=properties, **settings)

def PutAzureCosmosDBRecord(name: str = 'PutAzureCosmosDBRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.cosmos.document.PutAzureCosmosDBRecord', name, properties=properties, **settings)

def PutAzureDataExplorer(name: str = 'PutAzureDataExplorer', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.data.explorer.PutAzureDataExplorer', name, properties=properties, **settings)

def QueryAzureDataExplorer(name: str = 'QueryAzureDataExplorer', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.data.explorer.QueryAzureDataExplorer', name, properties=properties, **settings)

def ConsumeAzureEventHub(name: str = 'ConsumeAzureEventHub', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.eventhub.ConsumeAzureEventHub', name, properties=properties, **settings)

def GetAzureEventHub(name: str = 'GetAzureEventHub', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.eventhub.GetAzureEventHub', name, properties=properties, **settings)

def PutAzureEventHub(name: str = 'PutAzureEventHub', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.eventhub.PutAzureEventHub', name, properties=properties, **settings)

def CopyAzureBlobStorage_v12(name: str = 'CopyAzureBlobStorage_v12', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.CopyAzureBlobStorage_v12', name, properties=properties, **settings)

def DeleteAzureBlobStorage_v12(name: str = 'DeleteAzureBlobStorage_v12', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.DeleteAzureBlobStorage_v12', name, properties=properties, **settings)

def DeleteAzureDataLakeStorage(name: str = 'DeleteAzureDataLakeStorage', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.DeleteAzureDataLakeStorage', name, properties=properties, **settings)

def FetchAzureBlobStorage_v12(name: str = 'FetchAzureBlobStorage_v12', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.FetchAzureBlobStorage_v12', name, properties=properties, **settings)

def FetchAzureDataLakeStorage(name: str = 'FetchAzureDataLakeStorage', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.FetchAzureDataLakeStorage', name, properties=properties, **settings)

def ListAzureBlobStorage_v12(name: str = 'ListAzureBlobStorage_v12', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.ListAzureBlobStorage_v12', name, properties=properties, **settings)

def ListAzureDataLakeStorage(name: str = 'ListAzureDataLakeStorage', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.ListAzureDataLakeStorage', name, properties=properties, **settings)

def MoveAzureDataLakeStorage(name: str = 'MoveAzureDataLakeStorage', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.MoveAzureDataLakeStorage', name, properties=properties, **settings)

def PutAzureBlobStorage_v12(name: str = 'PutAzureBlobStorage_v12', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.PutAzureBlobStorage_v12', name, properties=properties, **settings)

def PutAzureDataLakeStorage(name: str = 'PutAzureDataLakeStorage', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.PutAzureDataLakeStorage', name, properties=properties, **settings)

def GetAzureQueueStorage_v12(name: str = 'GetAzureQueueStorage_v12', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.queue.GetAzureQueueStorage_v12', name, properties=properties, **settings)

def PutAzureQueueStorage_v12(name: str = 'PutAzureQueueStorage_v12', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.azure.storage.queue.PutAzureQueueStorage_v12', name, properties=properties, **settings)

def ConsumeBoxEnterpriseEvents(name: str = 'ConsumeBoxEnterpriseEvents', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.ConsumeBoxEnterpriseEvents', name, properties=properties, **settings)

def ConsumeBoxEvents(name: str = 'ConsumeBoxEvents', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.ConsumeBoxEvents', name, properties=properties, **settings)

def CreateBoxFileMetadataInstance(name: str = 'CreateBoxFileMetadataInstance', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.CreateBoxFileMetadataInstance', name, properties=properties, **settings)

def CreateBoxMetadataTemplate(name: str = 'CreateBoxMetadataTemplate', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.CreateBoxMetadataTemplate', name, properties=properties, **settings)

def DeleteBoxFileMetadataInstance(name: str = 'DeleteBoxFileMetadataInstance', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.DeleteBoxFileMetadataInstance', name, properties=properties, **settings)

def ExtractStructuredBoxFileMetadata(name: str = 'ExtractStructuredBoxFileMetadata', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.ExtractStructuredBoxFileMetadata', name, properties=properties, **settings)

def FetchBoxFile(name: str = 'FetchBoxFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.FetchBoxFile', name, properties=properties, **settings)

def FetchBoxFileInfo(name: str = 'FetchBoxFileInfo', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.FetchBoxFileInfo', name, properties=properties, **settings)

def FetchBoxFileMetadataInstance(name: str = 'FetchBoxFileMetadataInstance', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.FetchBoxFileMetadataInstance', name, properties=properties, **settings)

def FetchBoxFileRepresentation(name: str = 'FetchBoxFileRepresentation', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.FetchBoxFileRepresentation', name, properties=properties, **settings)

def GetBoxFileCollaborators(name: str = 'GetBoxFileCollaborators', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.GetBoxFileCollaborators', name, properties=properties, **settings)

def GetBoxGroupMembers(name: str = 'GetBoxGroupMembers', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.GetBoxGroupMembers', name, properties=properties, **settings)

def ListBoxFile(name: str = 'ListBoxFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.ListBoxFile', name, properties=properties, **settings)

def ListBoxFileInfo(name: str = 'ListBoxFileInfo', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.ListBoxFileInfo', name, properties=properties, **settings)

def ListBoxFileMetadataInstances(name: str = 'ListBoxFileMetadataInstances', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.ListBoxFileMetadataInstances', name, properties=properties, **settings)

def ListBoxFileMetadataTemplates(name: str = 'ListBoxFileMetadataTemplates', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.ListBoxFileMetadataTemplates', name, properties=properties, **settings)

def PutBoxFile(name: str = 'PutBoxFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.PutBoxFile', name, properties=properties, **settings)

def UpdateBoxFileMetadataInstance(name: str = 'UpdateBoxFileMetadataInstance', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.box.UpdateBoxFileMetadataInstance', name, properties=properties, **settings)

def DecryptContentAge(name: str = 'DecryptContentAge', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.cipher.DecryptContentAge', name, properties=properties, **settings)

def EncryptContentAge(name: str = 'EncryptContentAge', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.cipher.EncryptContentAge', name, properties=properties, **settings)

def VerifyContentMAC(name: str = 'VerifyContentMAC', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.cipher.VerifyContentMAC', name, properties=properties, **settings)

def ModifyCompression(name: str = 'ModifyCompression', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.compress.ModifyCompression', name, properties=properties, **settings)

def FetchDropbox(name: str = 'FetchDropbox', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.dropbox.FetchDropbox', name, properties=properties, **settings)

def ListDropbox(name: str = 'ListDropbox', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.dropbox.ListDropbox', name, properties=properties, **settings)

def PutDropbox(name: str = 'PutDropbox', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.dropbox.PutDropbox', name, properties=properties, **settings)

def ConsumeElasticsearch(name: str = 'ConsumeElasticsearch', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.elasticsearch.ConsumeElasticsearch', name, properties=properties, **settings)

def DeleteByQueryElasticsearch(name: str = 'DeleteByQueryElasticsearch', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.elasticsearch.DeleteByQueryElasticsearch', name, properties=properties, **settings)

def GetElasticsearch(name: str = 'GetElasticsearch', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.elasticsearch.GetElasticsearch', name, properties=properties, **settings)

def JsonQueryElasticsearch(name: str = 'JsonQueryElasticsearch', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.elasticsearch.JsonQueryElasticsearch', name, properties=properties, **settings)

def PaginatedJsonQueryElasticsearch(name: str = 'PaginatedJsonQueryElasticsearch', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.elasticsearch.PaginatedJsonQueryElasticsearch', name, properties=properties, **settings)

def PutElasticsearchJson(name: str = 'PutElasticsearchJson', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.elasticsearch.PutElasticsearchJson', name, properties=properties, **settings)

def PutElasticsearchRecord(name: str = 'PutElasticsearchRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.elasticsearch.PutElasticsearchRecord', name, properties=properties, **settings)

def SearchElasticsearch(name: str = 'SearchElasticsearch', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.elasticsearch.SearchElasticsearch', name, properties=properties, **settings)

def UpdateByQueryElasticsearch(name: str = 'UpdateByQueryElasticsearch', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.elasticsearch.UpdateByQueryElasticsearch', name, properties=properties, **settings)

def ConsumeIMAP(name: str = 'ConsumeIMAP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.email.ConsumeIMAP', name, properties=properties, **settings)

def ConsumePOP3(name: str = 'ConsumePOP3', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.email.ConsumePOP3', name, properties=properties, **settings)

def ExtractEmailAttachments(name: str = 'ExtractEmailAttachments', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.email.ExtractEmailAttachments', name, properties=properties, **settings)

def ExtractEmailHeaders(name: str = 'ExtractEmailHeaders', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.email.ExtractEmailHeaders', name, properties=properties, **settings)

def ParseEvtx(name: str = 'ParseEvtx', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.evtx.ParseEvtx', name, properties=properties, **settings)

def SplitExcel(name: str = 'SplitExcel', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.excel.SplitExcel', name, properties=properties, **settings)

def PutBigQuery(name: str = 'PutBigQuery', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.bigquery.PutBigQuery', name, properties=properties, **settings)

def FetchGoogleDrive(name: str = 'FetchGoogleDrive', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.drive.FetchGoogleDrive', name, properties=properties, **settings)

def ListGoogleDrive(name: str = 'ListGoogleDrive', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.drive.ListGoogleDrive', name, properties=properties, **settings)

def PutGoogleDrive(name: str = 'PutGoogleDrive', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.drive.PutGoogleDrive', name, properties=properties, **settings)

def ConsumeGCPubSub(name: str = 'ConsumeGCPubSub', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.pubsub.ConsumeGCPubSub', name, properties=properties, **settings)

def PublishGCPubSub(name: str = 'PublishGCPubSub', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.pubsub.PublishGCPubSub', name, properties=properties, **settings)

def DeleteGCSObject(name: str = 'DeleteGCSObject', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.storage.DeleteGCSObject', name, properties=properties, **settings)

def FetchGCSObject(name: str = 'FetchGCSObject', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.storage.FetchGCSObject', name, properties=properties, **settings)

def ListGCSBucket(name: str = 'ListGCSBucket', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.storage.ListGCSBucket', name, properties=properties, **settings)

def PutGCSObject(name: str = 'PutGCSObject', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.storage.PutGCSObject', name, properties=properties, **settings)

def GetGcpVisionAnnotateFilesOperationStatus(name: str = 'GetGcpVisionAnnotateFilesOperationStatus', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.vision.GetGcpVisionAnnotateFilesOperationStatus', name, properties=properties, **settings)

def GetGcpVisionAnnotateImagesOperationStatus(name: str = 'GetGcpVisionAnnotateImagesOperationStatus', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.vision.GetGcpVisionAnnotateImagesOperationStatus', name, properties=properties, **settings)

def StartGcpVisionAnnotateFilesOperation(name: str = 'StartGcpVisionAnnotateFilesOperation', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.vision.StartGcpVisionAnnotateFilesOperation', name, properties=properties, **settings)

def StartGcpVisionAnnotateImagesOperation(name: str = 'StartGcpVisionAnnotateImagesOperation', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.gcp.vision.StartGcpVisionAnnotateImagesOperation', name, properties=properties, **settings)

def GeohashRecord(name: str = 'GeohashRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.geohash.GeohashRecord', name, properties=properties, **settings)

def ExecuteGroovyScript(name: str = 'ExecuteGroovyScript', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.groovyx.ExecuteGroovyScript', name, properties=properties, **settings)

def ExtractHL7Attributes(name: str = 'ExtractHL7Attributes', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.hl7.ExtractHL7Attributes', name, properties=properties, **settings)

def RouteHL7(name: str = 'RouteHL7', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.hl7.RouteHL7', name, properties=properties, **settings)

def GetHubSpot(name: str = 'GetHubSpot', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.hubspot.GetHubSpot', name, properties=properties, **settings)

def PutIcebergRecord(name: str = 'PutIcebergRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.iceberg.PutIcebergRecord', name, properties=properties, **settings)

def JoltTransformJSON(name: str = 'JoltTransformJSON', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.jolt.JoltTransformJSON', name, properties=properties, **settings)

def JoltTransformRecord(name: str = 'JoltTransformRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.jolt.JoltTransformRecord', name, properties=properties, **settings)

def JSLTTransformJSON(name: str = 'JSLTTransformJSON', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.jslt.JSLTTransformJSON', name, properties=properties, **settings)

def DeleteMongo(name: str = 'DeleteMongo', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mongodb.DeleteMongo', name, properties=properties, **settings)

def GetMongo(name: str = 'GetMongo', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mongodb.GetMongo', name, properties=properties, **settings)

def GetMongoRecord(name: str = 'GetMongoRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mongodb.GetMongoRecord', name, properties=properties, **settings)

def PutMongo(name: str = 'PutMongo', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mongodb.PutMongo', name, properties=properties, **settings)

def PutMongoBulkOperations(name: str = 'PutMongoBulkOperations', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mongodb.PutMongoBulkOperations', name, properties=properties, **settings)

def PutMongoRecord(name: str = 'PutMongoRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mongodb.PutMongoRecord', name, properties=properties, **settings)

def RunMongoAggregation(name: str = 'RunMongoAggregation', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mongodb.RunMongoAggregation', name, properties=properties, **settings)

def DeleteGridFS(name: str = 'DeleteGridFS', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mongodb.gridfs.DeleteGridFS', name, properties=properties, **settings)

def FetchGridFS(name: str = 'FetchGridFS', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mongodb.gridfs.FetchGridFS', name, properties=properties, **settings)

def PutGridFS(name: str = 'PutGridFS', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mongodb.gridfs.PutGridFS', name, properties=properties, **settings)

def ConsumeMQTT(name: str = 'ConsumeMQTT', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mqtt.ConsumeMQTT', name, properties=properties, **settings)

def PublishMQTT(name: str = 'PublishMQTT', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.mqtt.PublishMQTT', name, properties=properties, **settings)

def ParseNetflowv5(name: str = 'ParseNetflowv5', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.network.ParseNetflowv5', name, properties=properties, **settings)

def SplitPCAP(name: str = 'SplitPCAP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.network.pcap.SplitPCAP', name, properties=properties, **settings)

def ListenOTLP(name: str = 'ListenOTLP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.opentelemetry.ListenOTLP', name, properties=properties, **settings)

def DecryptContentPGP(name: str = 'DecryptContentPGP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.pgp.DecryptContentPGP', name, properties=properties, **settings)

def EncryptContentPGP(name: str = 'EncryptContentPGP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.pgp.EncryptContentPGP', name, properties=properties, **settings)

def SignContentPGP(name: str = 'SignContentPGP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.pgp.SignContentPGP', name, properties=properties, **settings)

def VerifyContentPGP(name: str = 'VerifyContentPGP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.pgp.VerifyContentPGP', name, properties=properties, **settings)

def PutSalesforceObject(name: str = 'PutSalesforceObject', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.salesforce.PutSalesforceObject', name, properties=properties, **settings)

def QuerySalesforceObject(name: str = 'QuerySalesforceObject', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.salesforce.QuerySalesforceObject', name, properties=properties, **settings)

def ExecuteScript(name: str = 'ExecuteScript', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.script.ExecuteScript', name, properties=properties, **settings)

def InvokeScriptedProcessor(name: str = 'InvokeScriptedProcessor', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.script.InvokeScriptedProcessor', name, properties=properties, **settings)

def ScriptedFilterRecord(name: str = 'ScriptedFilterRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.script.ScriptedFilterRecord', name, properties=properties, **settings)

def ScriptedPartitionRecord(name: str = 'ScriptedPartitionRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.script.ScriptedPartitionRecord', name, properties=properties, **settings)

def ScriptedTransformRecord(name: str = 'ScriptedTransformRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.script.ScriptedTransformRecord', name, properties=properties, **settings)

def ScriptedValidateRecord(name: str = 'ScriptedValidateRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.script.ScriptedValidateRecord', name, properties=properties, **settings)

def GetShopify(name: str = 'GetShopify', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.shopify.GetShopify', name, properties=properties, **settings)

def ConsumeSlack(name: str = 'ConsumeSlack', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.slack.ConsumeSlack', name, properties=properties, **settings)

def ListenSlack(name: str = 'ListenSlack', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.slack.ListenSlack', name, properties=properties, **settings)

def PublishSlack(name: str = 'PublishSlack', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.slack.PublishSlack', name, properties=properties, **settings)

def FetchSmb(name: str = 'FetchSmb', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.smb.FetchSmb', name, properties=properties, **settings)

def GetSmbFile(name: str = 'GetSmbFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.smb.GetSmbFile', name, properties=properties, **settings)

def ListSmb(name: str = 'ListSmb', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.smb.ListSmb', name, properties=properties, **settings)

def PutSmbFile(name: str = 'PutSmbFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.smb.PutSmbFile', name, properties=properties, **settings)

def GetSplunk(name: str = 'GetSplunk', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.splunk.GetSplunk', name, properties=properties, **settings)

def PutSplunk(name: str = 'PutSplunk', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.splunk.PutSplunk', name, properties=properties, **settings)

def PutSplunkHTTP(name: str = 'PutSplunkHTTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.splunk.PutSplunkHTTP', name, properties=properties, **settings)

def QuerySplunkIndexingStatus(name: str = 'QuerySplunkIndexingStatus', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.splunk.QuerySplunkIndexingStatus', name, properties=properties, **settings)

def AttributesToCSV(name: str = 'AttributesToCSV', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.AttributesToCSV', name, properties=properties, **settings)

def AttributesToJSON(name: str = 'AttributesToJSON', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.AttributesToJSON', name, properties=properties, **settings)

def CalculateRecordStats(name: str = 'CalculateRecordStats', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.CalculateRecordStats', name, properties=properties, **settings)

def CompressContent(name: str = 'CompressContent', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.CompressContent', name, properties=properties, **settings)

def ControlRate(name: str = 'ControlRate', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ControlRate', name, properties=properties, **settings)

def ConvertCharacterSet(name: str = 'ConvertCharacterSet', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ConvertCharacterSet', name, properties=properties, **settings)

def ConvertRecord(name: str = 'ConvertRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ConvertRecord', name, properties=properties, **settings)

def CountText(name: str = 'CountText', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.CountText', name, properties=properties, **settings)

def CryptographicHashContent(name: str = 'CryptographicHashContent', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.CryptographicHashContent', name, properties=properties, **settings)

def DebugFlow(name: str = 'DebugFlow', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.DebugFlow', name, properties=properties, **settings)

def DeduplicateRecord(name: str = 'DeduplicateRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.DeduplicateRecord', name, properties=properties, **settings)

def DeleteFile(name: str = 'DeleteFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.DeleteFile', name, properties=properties, **settings)

def DeleteSFTP(name: str = 'DeleteSFTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.DeleteSFTP', name, properties=properties, **settings)

def DetectDuplicate(name: str = 'DetectDuplicate', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.DetectDuplicate', name, properties=properties, **settings)

def DistributeLoad(name: str = 'DistributeLoad', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.DistributeLoad', name, properties=properties, **settings)

def DuplicateFlowFile(name: str = 'DuplicateFlowFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.DuplicateFlowFile', name, properties=properties, **settings)

def EncodeContent(name: str = 'EncodeContent', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.EncodeContent', name, properties=properties, **settings)

def EnforceOrder(name: str = 'EnforceOrder', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.EnforceOrder', name, properties=properties, **settings)

def EvaluateJsonPath(name: str = 'EvaluateJsonPath', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.EvaluateJsonPath', name, properties=properties, **settings)

def EvaluateXPath(name: str = 'EvaluateXPath', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.EvaluateXPath', name, properties=properties, **settings)

def EvaluateXQuery(name: str = 'EvaluateXQuery', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.EvaluateXQuery', name, properties=properties, **settings)

def ExecuteProcess(name: str = 'ExecuteProcess', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ExecuteProcess', name, properties=properties, **settings)

def ExecuteSQL(name: str = 'ExecuteSQL', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ExecuteSQL', name, properties=properties, **settings)

def ExecuteSQLRecord(name: str = 'ExecuteSQLRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ExecuteSQLRecord', name, properties=properties, **settings)

def ExecuteStreamCommand(name: str = 'ExecuteStreamCommand', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ExecuteStreamCommand', name, properties=properties, **settings)

def ExtractGrok(name: str = 'ExtractGrok', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ExtractGrok', name, properties=properties, **settings)

def ExtractRecordSchema(name: str = 'ExtractRecordSchema', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ExtractRecordSchema', name, properties=properties, **settings)

def ExtractText(name: str = 'ExtractText', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ExtractText', name, properties=properties, **settings)

def FetchDistributedMapCache(name: str = 'FetchDistributedMapCache', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.FetchDistributedMapCache', name, properties=properties, **settings)

def FetchFTP(name: str = 'FetchFTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.FetchFTP', name, properties=properties, **settings)

def FetchFile(name: str = 'FetchFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.FetchFile', name, properties=properties, **settings)

def FetchSFTP(name: str = 'FetchSFTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.FetchSFTP', name, properties=properties, **settings)

def FilterAttribute(name: str = 'FilterAttribute', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.FilterAttribute', name, properties=properties, **settings)

def FlattenJson(name: str = 'FlattenJson', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.FlattenJson', name, properties=properties, **settings)

def ForkEnrichment(name: str = 'ForkEnrichment', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ForkEnrichment', name, properties=properties, **settings)

def ForkRecord(name: str = 'ForkRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ForkRecord', name, properties=properties, **settings)

def GenerateFlowFile(name: str = 'GenerateFlowFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.GenerateFlowFile', name, properties=properties, **settings)

def GenerateRecord(name: str = 'GenerateRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.GenerateRecord', name, properties=properties, **settings)

def GenerateTableFetch(name: str = 'GenerateTableFetch', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.GenerateTableFetch', name, properties=properties, **settings)

def GetFTP(name: str = 'GetFTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.GetFTP', name, properties=properties, **settings)

def GetFile(name: str = 'GetFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.GetFile', name, properties=properties, **settings)

def GetFileResource(name: str = 'GetFileResource', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.GetFileResource', name, properties=properties, **settings)

def GetSFTP(name: str = 'GetSFTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.GetSFTP', name, properties=properties, **settings)

def HandleHttpRequest(name: str = 'HandleHttpRequest', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.HandleHttpRequest', name, properties=properties, **settings)

def HandleHttpResponse(name: str = 'HandleHttpResponse', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.HandleHttpResponse', name, properties=properties, **settings)

def IdentifyMimeType(name: str = 'IdentifyMimeType', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.IdentifyMimeType', name, properties=properties, **settings)

def InvokeHTTP(name: str = 'InvokeHTTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.InvokeHTTP', name, properties=properties, **settings)

def JoinEnrichment(name: str = 'JoinEnrichment', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.JoinEnrichment', name, properties=properties, **settings)

def ListDatabaseTables(name: str = 'ListDatabaseTables', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ListDatabaseTables', name, properties=properties, **settings)

def ListFTP(name: str = 'ListFTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ListFTP', name, properties=properties, **settings)

def ListFile(name: str = 'ListFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ListFile', name, properties=properties, **settings)

def ListSFTP(name: str = 'ListSFTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ListSFTP', name, properties=properties, **settings)

def ListenFTP(name: str = 'ListenFTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ListenFTP', name, properties=properties, **settings)

def ListenHTTP(name: str = 'ListenHTTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ListenHTTP', name, properties=properties, **settings)

def ListenSyslog(name: str = 'ListenSyslog', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ListenSyslog', name, properties=properties, **settings)

def ListenTCP(name: str = 'ListenTCP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ListenTCP', name, properties=properties, **settings)

def ListenUDP(name: str = 'ListenUDP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ListenUDP', name, properties=properties, **settings)

def ListenUDPRecord(name: str = 'ListenUDPRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ListenUDPRecord', name, properties=properties, **settings)

def LogAttribute(name: str = 'LogAttribute', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.LogAttribute', name, properties=properties, **settings)

def LogMessage(name: str = 'LogMessage', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.LogMessage', name, properties=properties, **settings)

def LookupAttribute(name: str = 'LookupAttribute', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.LookupAttribute', name, properties=properties, **settings)

def LookupRecord(name: str = 'LookupRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.LookupRecord', name, properties=properties, **settings)

def MergeContent(name: str = 'MergeContent', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.MergeContent', name, properties=properties, **settings)

def MergeRecord(name: str = 'MergeRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.MergeRecord', name, properties=properties, **settings)

def ModifyBytes(name: str = 'ModifyBytes', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ModifyBytes', name, properties=properties, **settings)

def MonitorActivity(name: str = 'MonitorActivity', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.MonitorActivity', name, properties=properties, **settings)

def Notify(name: str = 'Notify', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.Notify', name, properties=properties, **settings)

def PackageFlowFile(name: str = 'PackageFlowFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PackageFlowFile', name, properties=properties, **settings)

def ParseSyslog(name: str = 'ParseSyslog', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ParseSyslog', name, properties=properties, **settings)

def ParseSyslog5424(name: str = 'ParseSyslog5424', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ParseSyslog5424', name, properties=properties, **settings)

def PartitionRecord(name: str = 'PartitionRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PartitionRecord', name, properties=properties, **settings)

def PutDatabaseRecord(name: str = 'PutDatabaseRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PutDatabaseRecord', name, properties=properties, **settings)

def PutDistributedMapCache(name: str = 'PutDistributedMapCache', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PutDistributedMapCache', name, properties=properties, **settings)

def PutEmail(name: str = 'PutEmail', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PutEmail', name, properties=properties, **settings)

def PutFTP(name: str = 'PutFTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PutFTP', name, properties=properties, **settings)

def PutFile(name: str = 'PutFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PutFile', name, properties=properties, **settings)

def PutRecord(name: str = 'PutRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PutRecord', name, properties=properties, **settings)

def PutSFTP(name: str = 'PutSFTP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PutSFTP', name, properties=properties, **settings)

def PutSQL(name: str = 'PutSQL', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PutSQL', name, properties=properties, **settings)

def PutSyslog(name: str = 'PutSyslog', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PutSyslog', name, properties=properties, **settings)

def PutTCP(name: str = 'PutTCP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PutTCP', name, properties=properties, **settings)

def PutUDP(name: str = 'PutUDP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.PutUDP', name, properties=properties, **settings)

def QueryDatabaseTable(name: str = 'QueryDatabaseTable', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.QueryDatabaseTable', name, properties=properties, **settings)

def QueryDatabaseTableRecord(name: str = 'QueryDatabaseTableRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.QueryDatabaseTableRecord', name, properties=properties, **settings)

def QueryRecord(name: str = 'QueryRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.QueryRecord', name, properties=properties, **settings)

def RemoveRecordField(name: str = 'RemoveRecordField', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.RemoveRecordField', name, properties=properties, **settings)

def RenameRecordField(name: str = 'RenameRecordField', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.RenameRecordField', name, properties=properties, **settings)

def ReplaceText(name: str = 'ReplaceText', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ReplaceText', name, properties=properties, **settings)

def ReplaceTextWithMapping(name: str = 'ReplaceTextWithMapping', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ReplaceTextWithMapping', name, properties=properties, **settings)

def RetryFlowFile(name: str = 'RetryFlowFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.RetryFlowFile', name, properties=properties, **settings)

def RouteOnAttribute(name: str = 'RouteOnAttribute', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.RouteOnAttribute', name, properties=properties, **settings)

def RouteOnContent(name: str = 'RouteOnContent', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.RouteOnContent', name, properties=properties, **settings)

def RouteText(name: str = 'RouteText', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.RouteText', name, properties=properties, **settings)

def SampleRecord(name: str = 'SampleRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.SampleRecord', name, properties=properties, **settings)

def ScanAttribute(name: str = 'ScanAttribute', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ScanAttribute', name, properties=properties, **settings)

def ScanContent(name: str = 'ScanContent', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ScanContent', name, properties=properties, **settings)

def SegmentContent(name: str = 'SegmentContent', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.SegmentContent', name, properties=properties, **settings)

def SplitContent(name: str = 'SplitContent', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.SplitContent', name, properties=properties, **settings)

def SplitJson(name: str = 'SplitJson', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.SplitJson', name, properties=properties, **settings)

def SplitRecord(name: str = 'SplitRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.SplitRecord', name, properties=properties, **settings)

def SplitText(name: str = 'SplitText', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.SplitText', name, properties=properties, **settings)

def SplitXml(name: str = 'SplitXml', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.SplitXml', name, properties=properties, **settings)

def TailFile(name: str = 'TailFile', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.TailFile', name, properties=properties, **settings)

def TransformXml(name: str = 'TransformXml', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.TransformXml', name, properties=properties, **settings)

def UnpackContent(name: str = 'UnpackContent', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.UnpackContent', name, properties=properties, **settings)

def UpdateCounter(name: str = 'UpdateCounter', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.UpdateCounter', name, properties=properties, **settings)

def UpdateDatabaseTable(name: str = 'UpdateDatabaseTable', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.UpdateDatabaseTable', name, properties=properties, **settings)

def UpdateRecord(name: str = 'UpdateRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.UpdateRecord', name, properties=properties, **settings)

def ValidateCsv(name: str = 'ValidateCsv', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ValidateCsv', name, properties=properties, **settings)

def ValidateJson(name: str = 'ValidateJson', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ValidateJson', name, properties=properties, **settings)

def ValidateRecord(name: str = 'ValidateRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ValidateRecord', name, properties=properties, **settings)

def ValidateXml(name: str = 'ValidateXml', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.ValidateXml', name, properties=properties, **settings)

def Wait(name: str = 'Wait', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.standard.Wait', name, properties=properties, **settings)

def AttributeRollingWindow(name: str = 'AttributeRollingWindow', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.stateful.analysis.AttributeRollingWindow', name, properties=properties, **settings)

def ConsumeTwitter(name: str = 'ConsumeTwitter', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.twitter.ConsumeTwitter', name, properties=properties, **settings)

def ConnectWebSocket(name: str = 'ConnectWebSocket', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.websocket.ConnectWebSocket', name, properties=properties, **settings)

def ListenWebSocket(name: str = 'ListenWebSocket', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.websocket.ListenWebSocket', name, properties=properties, **settings)

def PutWebSocket(name: str = 'PutWebSocket', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.websocket.PutWebSocket', name, properties=properties, **settings)

def ConsumeWindowsEventLog(name: str = 'ConsumeWindowsEventLog', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.windows.event.log.ConsumeWindowsEventLog', name, properties=properties, **settings)

def GetWorkdayReport(name: str = 'GetWorkdayReport', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.workday.GetWorkdayReport', name, properties=properties, **settings)

def GetZendesk(name: str = 'GetZendesk', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.zendesk.GetZendesk', name, properties=properties, **settings)

def PutZendeskTicket(name: str = 'PutZendeskTicket', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.processors.zendesk.PutZendeskTicket', name, properties=properties, **settings)

def PutRedisHashRecord(name: str = 'PutRedisHashRecord', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.redis.processor.PutRedisHashRecord', name, properties=properties, **settings)

def GetSNMP(name: str = 'GetSNMP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.snmp.processors.GetSNMP', name, properties=properties, **settings)

def ListenTrapSNMP(name: str = 'ListenTrapSNMP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.snmp.processors.ListenTrapSNMP', name, properties=properties, **settings)

def SendTrapSNMP(name: str = 'SendTrapSNMP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.snmp.processors.SendTrapSNMP', name, properties=properties, **settings)

def SetSNMP(name: str = 'SetSNMP', properties: Optional[Dict[str, Any]] = None, **settings: Any) -> Processor:
    return _processor('org.apache.nifi.snmp.processors.SetSNMP', name, properties=properties, **settings)

ALL = [
    ConsumeAMQP,
    PublishAMQP,
    CaptureChangeMySQL,
    ConsumeJMS,
    PublishJMS,
    ConsumeKafka,
    PublishKafka,
    GeoEnrichIP,
    GeoEnrichIPRecord,
    ISPEnrichIP,
    QueryAirtableTable,
    GetAsanaObject,
    UpdateAttribute,
    ExtractAvroMetadata,
    SplitAvro,
    PutCloudWatchMetric,
    DeleteDynamoDB,
    GetDynamoDB,
    PutDynamoDB,
    PutDynamoDBRecord,
    ConsumeKinesis,
    PutKinesisFirehose,
    ConsumeKinesisStream,
    PutKinesisStream,
    PutLambda,
    GetAwsPollyJobStatus,
    StartAwsPollyJob,
    GetAwsTextractJobStatus,
    StartAwsTextractJob,
    GetAwsTranscribeJobStatus,
    StartAwsTranscribeJob,
    GetAwsTranslateJobStatus,
    StartAwsTranslateJob,
    CopyS3Object,
    DeleteS3Object,
    FetchS3Object,
    GetS3ObjectMetadata,
    GetS3ObjectTags,
    ListS3,
    PutS3Object,
    TagS3Object,
    PutSNS,
    DeleteSQS,
    GetSQS,
    PutSQS,
    PutAzureCosmosDBRecord,
    PutAzureDataExplorer,
    QueryAzureDataExplorer,
    ConsumeAzureEventHub,
    GetAzureEventHub,
    PutAzureEventHub,
    CopyAzureBlobStorage_v12,
    DeleteAzureBlobStorage_v12,
    DeleteAzureDataLakeStorage,
    FetchAzureBlobStorage_v12,
    FetchAzureDataLakeStorage,
    ListAzureBlobStorage_v12,
    ListAzureDataLakeStorage,
    MoveAzureDataLakeStorage,
    PutAzureBlobStorage_v12,
    PutAzureDataLakeStorage,
    GetAzureQueueStorage_v12,
    PutAzureQueueStorage_v12,
    ConsumeBoxEnterpriseEvents,
    ConsumeBoxEvents,
    CreateBoxFileMetadataInstance,
    CreateBoxMetadataTemplate,
    DeleteBoxFileMetadataInstance,
    ExtractStructuredBoxFileMetadata,
    FetchBoxFile,
    FetchBoxFileInfo,
    FetchBoxFileMetadataInstance,
    FetchBoxFileRepresentation,
    GetBoxFileCollaborators,
    GetBoxGroupMembers,
    ListBoxFile,
    ListBoxFileInfo,
    ListBoxFileMetadataInstances,
    ListBoxFileMetadataTemplates,
    PutBoxFile,
    UpdateBoxFileMetadataInstance,
    DecryptContentAge,
    EncryptContentAge,
    VerifyContentMAC,
    ModifyCompression,
    FetchDropbox,
    ListDropbox,
    PutDropbox,
    ConsumeElasticsearch,
    DeleteByQueryElasticsearch,
    GetElasticsearch,
    JsonQueryElasticsearch,
    PaginatedJsonQueryElasticsearch,
    PutElasticsearchJson,
    PutElasticsearchRecord,
    SearchElasticsearch,
    UpdateByQueryElasticsearch,
    ConsumeIMAP,
    ConsumePOP3,
    ExtractEmailAttachments,
    ExtractEmailHeaders,
    ParseEvtx,
    SplitExcel,
    PutBigQuery,
    FetchGoogleDrive,
    ListGoogleDrive,
    PutGoogleDrive,
    ConsumeGCPubSub,
    PublishGCPubSub,
    DeleteGCSObject,
    FetchGCSObject,
    ListGCSBucket,
    PutGCSObject,
    GetGcpVisionAnnotateFilesOperationStatus,
    GetGcpVisionAnnotateImagesOperationStatus,
    StartGcpVisionAnnotateFilesOperation,
    StartGcpVisionAnnotateImagesOperation,
    GeohashRecord,
    ExecuteGroovyScript,
    ExtractHL7Attributes,
    RouteHL7,
    GetHubSpot,
    PutIcebergRecord,
    JoltTransformJSON,
    JoltTransformRecord,
    JSLTTransformJSON,
    DeleteMongo,
    GetMongo,
    GetMongoRecord,
    PutMongo,
    PutMongoBulkOperations,
    PutMongoRecord,
    RunMongoAggregation,
    DeleteGridFS,
    FetchGridFS,
    PutGridFS,
    ConsumeMQTT,
    PublishMQTT,
    ParseNetflowv5,
    SplitPCAP,
    ListenOTLP,
    DecryptContentPGP,
    EncryptContentPGP,
    SignContentPGP,
    VerifyContentPGP,
    PutSalesforceObject,
    QuerySalesforceObject,
    ExecuteScript,
    InvokeScriptedProcessor,
    ScriptedFilterRecord,
    ScriptedPartitionRecord,
    ScriptedTransformRecord,
    ScriptedValidateRecord,
    GetShopify,
    ConsumeSlack,
    ListenSlack,
    PublishSlack,
    FetchSmb,
    GetSmbFile,
    ListSmb,
    PutSmbFile,
    GetSplunk,
    PutSplunk,
    PutSplunkHTTP,
    QuerySplunkIndexingStatus,
    AttributesToCSV,
    AttributesToJSON,
    CalculateRecordStats,
    CompressContent,
    ControlRate,
    ConvertCharacterSet,
    ConvertRecord,
    CountText,
    CryptographicHashContent,
    DebugFlow,
    DeduplicateRecord,
    DeleteFile,
    DeleteSFTP,
    DetectDuplicate,
    DistributeLoad,
    DuplicateFlowFile,
    EncodeContent,
    EnforceOrder,
    EvaluateJsonPath,
    EvaluateXPath,
    EvaluateXQuery,
    ExecuteProcess,
    ExecuteSQL,
    ExecuteSQLRecord,
    ExecuteStreamCommand,
    ExtractGrok,
    ExtractRecordSchema,
    ExtractText,
    FetchDistributedMapCache,
    FetchFTP,
    FetchFile,
    FetchSFTP,
    FilterAttribute,
    FlattenJson,
    ForkEnrichment,
    ForkRecord,
    GenerateFlowFile,
    GenerateRecord,
    GenerateTableFetch,
    GetFTP,
    GetFile,
    GetFileResource,
    GetSFTP,
    HandleHttpRequest,
    HandleHttpResponse,
    IdentifyMimeType,
    InvokeHTTP,
    JoinEnrichment,
    ListDatabaseTables,
    ListFTP,
    ListFile,
    ListSFTP,
    ListenFTP,
    ListenHTTP,
    ListenSyslog,
    ListenTCP,
    ListenUDP,
    ListenUDPRecord,
    LogAttribute,
    LogMessage,
    LookupAttribute,
    LookupRecord,
    MergeContent,
    MergeRecord,
    ModifyBytes,
    MonitorActivity,
    Notify,
    PackageFlowFile,
    ParseSyslog,
    ParseSyslog5424,
    PartitionRecord,
    PutDatabaseRecord,
    PutDistributedMapCache,
    PutEmail,
    PutFTP,
    PutFile,
    PutRecord,
    PutSFTP,
    PutSQL,
    PutSyslog,
    PutTCP,
    PutUDP,
    QueryDatabaseTable,
    QueryDatabaseTableRecord,
    QueryRecord,
    RemoveRecordField,
    RenameRecordField,
    ReplaceText,
    ReplaceTextWithMapping,
    RetryFlowFile,
    RouteOnAttribute,
    RouteOnContent,
    RouteText,
    SampleRecord,
    ScanAttribute,
    ScanContent,
    SegmentContent,
    SplitContent,
    SplitJson,
    SplitRecord,
    SplitText,
    SplitXml,
    TailFile,
    TransformXml,
    UnpackContent,
    UpdateCounter,
    UpdateDatabaseTable,
    UpdateRecord,
    ValidateCsv,
    ValidateJson,
    ValidateRecord,
    ValidateXml,
    Wait,
    AttributeRollingWindow,
    ConsumeTwitter,
    ConnectWebSocket,
    ListenWebSocket,
    PutWebSocket,
    ConsumeWindowsEventLog,
    GetWorkdayReport,
    GetZendesk,
    PutZendeskTicket,
    PutRedisHashRecord,
    GetSNMP,
    ListenTrapSNMP,
    SendTrapSNMP,
    SetSNMP,
]

TYPES = [
    'org.apache.nifi.amqp.processors.ConsumeAMQP',
    'org.apache.nifi.amqp.processors.PublishAMQP',
    'org.apache.nifi.cdc.mysql.processors.CaptureChangeMySQL',
    'org.apache.nifi.jms.processors.ConsumeJMS',
    'org.apache.nifi.jms.processors.PublishJMS',
    'org.apache.nifi.kafka.processors.ConsumeKafka',
    'org.apache.nifi.kafka.processors.PublishKafka',
    'org.apache.nifi.processors.GeoEnrichIP',
    'org.apache.nifi.processors.GeoEnrichIPRecord',
    'org.apache.nifi.processors.ISPEnrichIP',
    'org.apache.nifi.processors.airtable.QueryAirtableTable',
    'org.apache.nifi.processors.asana.GetAsanaObject',
    'org.apache.nifi.processors.attributes.UpdateAttribute',
    'org.apache.nifi.processors.avro.ExtractAvroMetadata',
    'org.apache.nifi.processors.avro.SplitAvro',
    'org.apache.nifi.processors.aws.cloudwatch.PutCloudWatchMetric',
    'org.apache.nifi.processors.aws.dynamodb.DeleteDynamoDB',
    'org.apache.nifi.processors.aws.dynamodb.GetDynamoDB',
    'org.apache.nifi.processors.aws.dynamodb.PutDynamoDB',
    'org.apache.nifi.processors.aws.dynamodb.PutDynamoDBRecord',
    'org.apache.nifi.processors.aws.kinesis.ConsumeKinesis',
    'org.apache.nifi.processors.aws.kinesis.firehose.PutKinesisFirehose',
    'org.apache.nifi.processors.aws.kinesis.stream.ConsumeKinesisStream',
    'org.apache.nifi.processors.aws.kinesis.stream.PutKinesisStream',
    'org.apache.nifi.processors.aws.lambda.PutLambda',
    'org.apache.nifi.processors.aws.ml.polly.GetAwsPollyJobStatus',
    'org.apache.nifi.processors.aws.ml.polly.StartAwsPollyJob',
    'org.apache.nifi.processors.aws.ml.textract.GetAwsTextractJobStatus',
    'org.apache.nifi.processors.aws.ml.textract.StartAwsTextractJob',
    'org.apache.nifi.processors.aws.ml.transcribe.GetAwsTranscribeJobStatus',
    'org.apache.nifi.processors.aws.ml.transcribe.StartAwsTranscribeJob',
    'org.apache.nifi.processors.aws.ml.translate.GetAwsTranslateJobStatus',
    'org.apache.nifi.processors.aws.ml.translate.StartAwsTranslateJob',
    'org.apache.nifi.processors.aws.s3.CopyS3Object',
    'org.apache.nifi.processors.aws.s3.DeleteS3Object',
    'org.apache.nifi.processors.aws.s3.FetchS3Object',
    'org.apache.nifi.processors.aws.s3.GetS3ObjectMetadata',
    'org.apache.nifi.processors.aws.s3.GetS3ObjectTags',
    'org.apache.nifi.processors.aws.s3.ListS3',
    'org.apache.nifi.processors.aws.s3.PutS3Object',
    'org.apache.nifi.processors.aws.s3.TagS3Object',
    'org.apache.nifi.processors.aws.sns.PutSNS',
    'org.apache.nifi.processors.aws.sqs.DeleteSQS',
    'org.apache.nifi.processors.aws.sqs.GetSQS',
    'org.apache.nifi.processors.aws.sqs.PutSQS',
    'org.apache.nifi.processors.azure.cosmos.document.PutAzureCosmosDBRecord',
    'org.apache.nifi.processors.azure.data.explorer.PutAzureDataExplorer',
    'org.apache.nifi.processors.azure.data.explorer.QueryAzureDataExplorer',
    'org.apache.nifi.processors.azure.eventhub.ConsumeAzureEventHub',
    'org.apache.nifi.processors.azure.eventhub.GetAzureEventHub',
    'org.apache.nifi.processors.azure.eventhub.PutAzureEventHub',
    'org.apache.nifi.processors.azure.storage.CopyAzureBlobStorage_v12',
    'org.apache.nifi.processors.azure.storage.DeleteAzureBlobStorage_v12',
    'org.apache.nifi.processors.azure.storage.DeleteAzureDataLakeStorage',
    'org.apache.nifi.processors.azure.storage.FetchAzureBlobStorage_v12',
    'org.apache.nifi.processors.azure.storage.FetchAzureDataLakeStorage',
    'org.apache.nifi.processors.azure.storage.ListAzureBlobStorage_v12',
    'org.apache.nifi.processors.azure.storage.ListAzureDataLakeStorage',
    'org.apache.nifi.processors.azure.storage.MoveAzureDataLakeStorage',
    'org.apache.nifi.processors.azure.storage.PutAzureBlobStorage_v12',
    'org.apache.nifi.processors.azure.storage.PutAzureDataLakeStorage',
    'org.apache.nifi.processors.azure.storage.queue.GetAzureQueueStorage_v12',
    'org.apache.nifi.processors.azure.storage.queue.PutAzureQueueStorage_v12',
    'org.apache.nifi.processors.box.ConsumeBoxEnterpriseEvents',
    'org.apache.nifi.processors.box.ConsumeBoxEvents',
    'org.apache.nifi.processors.box.CreateBoxFileMetadataInstance',
    'org.apache.nifi.processors.box.CreateBoxMetadataTemplate',
    'org.apache.nifi.processors.box.DeleteBoxFileMetadataInstance',
    'org.apache.nifi.processors.box.ExtractStructuredBoxFileMetadata',
    'org.apache.nifi.processors.box.FetchBoxFile',
    'org.apache.nifi.processors.box.FetchBoxFileInfo',
    'org.apache.nifi.processors.box.FetchBoxFileMetadataInstance',
    'org.apache.nifi.processors.box.FetchBoxFileRepresentation',
    'org.apache.nifi.processors.box.GetBoxFileCollaborators',
    'org.apache.nifi.processors.box.GetBoxGroupMembers',
    'org.apache.nifi.processors.box.ListBoxFile',
    'org.apache.nifi.processors.box.ListBoxFileInfo',
    'org.apache.nifi.processors.box.ListBoxFileMetadataInstances',
    'org.apache.nifi.processors.box.ListBoxFileMetadataTemplates',
    'org.apache.nifi.processors.box.PutBoxFile',
    'org.apache.nifi.processors.box.UpdateBoxFileMetadataInstance',
    'org.apache.nifi.processors.cipher.DecryptContentAge',
    'org.apache.nifi.processors.cipher.EncryptContentAge',
    'org.apache.nifi.processors.cipher.VerifyContentMAC',
    'org.apache.nifi.processors.compress.ModifyCompression',
    'org.apache.nifi.processors.dropbox.FetchDropbox',
    'org.apache.nifi.processors.dropbox.ListDropbox',
    'org.apache.nifi.processors.dropbox.PutDropbox',
    'org.apache.nifi.processors.elasticsearch.ConsumeElasticsearch',
    'org.apache.nifi.processors.elasticsearch.DeleteByQueryElasticsearch',
    'org.apache.nifi.processors.elasticsearch.GetElasticsearch',
    'org.apache.nifi.processors.elasticsearch.JsonQueryElasticsearch',
    'org.apache.nifi.processors.elasticsearch.PaginatedJsonQueryElasticsearch',
    'org.apache.nifi.processors.elasticsearch.PutElasticsearchJson',
    'org.apache.nifi.processors.elasticsearch.PutElasticsearchRecord',
    'org.apache.nifi.processors.elasticsearch.SearchElasticsearch',
    'org.apache.nifi.processors.elasticsearch.UpdateByQueryElasticsearch',
    'org.apache.nifi.processors.email.ConsumeIMAP',
    'org.apache.nifi.processors.email.ConsumePOP3',
    'org.apache.nifi.processors.email.ExtractEmailAttachments',
    'org.apache.nifi.processors.email.ExtractEmailHeaders',
    'org.apache.nifi.processors.evtx.ParseEvtx',
    'org.apache.nifi.processors.excel.SplitExcel',
    'org.apache.nifi.processors.gcp.bigquery.PutBigQuery',
    'org.apache.nifi.processors.gcp.drive.FetchGoogleDrive',
    'org.apache.nifi.processors.gcp.drive.ListGoogleDrive',
    'org.apache.nifi.processors.gcp.drive.PutGoogleDrive',
    'org.apache.nifi.processors.gcp.pubsub.ConsumeGCPubSub',
    'org.apache.nifi.processors.gcp.pubsub.PublishGCPubSub',
    'org.apache.nifi.processors.gcp.storage.DeleteGCSObject',
    'org.apache.nifi.processors.gcp.storage.FetchGCSObject',
    'org.apache.nifi.processors.gcp.storage.ListGCSBucket',
    'org.apache.nifi.processors.gcp.storage.PutGCSObject',
    'org.apache.nifi.processors.gcp.vision.GetGcpVisionAnnotateFilesOperationStatus',
    'org.apache.nifi.processors.gcp.vision.GetGcpVisionAnnotateImagesOperationStatus',
    'org.apache.nifi.processors.gcp.vision.StartGcpVisionAnnotateFilesOperation',
    'org.apache.nifi.processors.gcp.vision.StartGcpVisionAnnotateImagesOperation',
    'org.apache.nifi.processors.geohash.GeohashRecord',
    'org.apache.nifi.processors.groovyx.ExecuteGroovyScript',
    'org.apache.nifi.processors.hl7.ExtractHL7Attributes',
    'org.apache.nifi.processors.hl7.RouteHL7',
    'org.apache.nifi.processors.hubspot.GetHubSpot',
    'org.apache.nifi.processors.iceberg.PutIcebergRecord',
    'org.apache.nifi.processors.jolt.JoltTransformJSON',
    'org.apache.nifi.processors.jolt.JoltTransformRecord',
    'org.apache.nifi.processors.jslt.JSLTTransformJSON',
    'org.apache.nifi.processors.mongodb.DeleteMongo',
    'org.apache.nifi.processors.mongodb.GetMongo',
    'org.apache.nifi.processors.mongodb.GetMongoRecord',
    'org.apache.nifi.processors.mongodb.PutMongo',
    'org.apache.nifi.processors.mongodb.PutMongoBulkOperations',
    'org.apache.nifi.processors.mongodb.PutMongoRecord',
    'org.apache.nifi.processors.mongodb.RunMongoAggregation',
    'org.apache.nifi.processors.mongodb.gridfs.DeleteGridFS',
    'org.apache.nifi.processors.mongodb.gridfs.FetchGridFS',
    'org.apache.nifi.processors.mongodb.gridfs.PutGridFS',
    'org.apache.nifi.processors.mqtt.ConsumeMQTT',
    'org.apache.nifi.processors.mqtt.PublishMQTT',
    'org.apache.nifi.processors.network.ParseNetflowv5',
    'org.apache.nifi.processors.network.pcap.SplitPCAP',
    'org.apache.nifi.processors.opentelemetry.ListenOTLP',
    'org.apache.nifi.processors.pgp.DecryptContentPGP',
    'org.apache.nifi.processors.pgp.EncryptContentPGP',
    'org.apache.nifi.processors.pgp.SignContentPGP',
    'org.apache.nifi.processors.pgp.VerifyContentPGP',
    'org.apache.nifi.processors.salesforce.PutSalesforceObject',
    'org.apache.nifi.processors.salesforce.QuerySalesforceObject',
    'org.apache.nifi.processors.script.ExecuteScript',
    'org.apache.nifi.processors.script.InvokeScriptedProcessor',
    'org.apache.nifi.processors.script.ScriptedFilterRecord',
    'org.apache.nifi.processors.script.ScriptedPartitionRecord',
    'org.apache.nifi.processors.script.ScriptedTransformRecord',
    'org.apache.nifi.processors.script.ScriptedValidateRecord',
    'org.apache.nifi.processors.shopify.GetShopify',
    'org.apache.nifi.processors.slack.ConsumeSlack',
    'org.apache.nifi.processors.slack.ListenSlack',
    'org.apache.nifi.processors.slack.PublishSlack',
    'org.apache.nifi.processors.smb.FetchSmb',
    'org.apache.nifi.processors.smb.GetSmbFile',
    'org.apache.nifi.processors.smb.ListSmb',
    'org.apache.nifi.processors.smb.PutSmbFile',
    'org.apache.nifi.processors.splunk.GetSplunk',
    'org.apache.nifi.processors.splunk.PutSplunk',
    'org.apache.nifi.processors.splunk.PutSplunkHTTP',
    'org.apache.nifi.processors.splunk.QuerySplunkIndexingStatus',
    'org.apache.nifi.processors.standard.AttributesToCSV',
    'org.apache.nifi.processors.standard.AttributesToJSON',
    'org.apache.nifi.processors.standard.CalculateRecordStats',
    'org.apache.nifi.processors.standard.CompressContent',
    'org.apache.nifi.processors.standard.ControlRate',
    'org.apache.nifi.processors.standard.ConvertCharacterSet',
    'org.apache.nifi.processors.standard.ConvertRecord',
    'org.apache.nifi.processors.standard.CountText',
    'org.apache.nifi.processors.standard.CryptographicHashContent',
    'org.apache.nifi.processors.standard.DebugFlow',
    'org.apache.nifi.processors.standard.DeduplicateRecord',
    'org.apache.nifi.processors.standard.DeleteFile',
    'org.apache.nifi.processors.standard.DeleteSFTP',
    'org.apache.nifi.processors.standard.DetectDuplicate',
    'org.apache.nifi.processors.standard.DistributeLoad',
    'org.apache.nifi.processors.standard.DuplicateFlowFile',
    'org.apache.nifi.processors.standard.EncodeContent',
    'org.apache.nifi.processors.standard.EnforceOrder',
    'org.apache.nifi.processors.standard.EvaluateJsonPath',
    'org.apache.nifi.processors.standard.EvaluateXPath',
    'org.apache.nifi.processors.standard.EvaluateXQuery',
    'org.apache.nifi.processors.standard.ExecuteProcess',
    'org.apache.nifi.processors.standard.ExecuteSQL',
    'org.apache.nifi.processors.standard.ExecuteSQLRecord',
    'org.apache.nifi.processors.standard.ExecuteStreamCommand',
    'org.apache.nifi.processors.standard.ExtractGrok',
    'org.apache.nifi.processors.standard.ExtractRecordSchema',
    'org.apache.nifi.processors.standard.ExtractText',
    'org.apache.nifi.processors.standard.FetchDistributedMapCache',
    'org.apache.nifi.processors.standard.FetchFTP',
    'org.apache.nifi.processors.standard.FetchFile',
    'org.apache.nifi.processors.standard.FetchSFTP',
    'org.apache.nifi.processors.standard.FilterAttribute',
    'org.apache.nifi.processors.standard.FlattenJson',
    'org.apache.nifi.processors.standard.ForkEnrichment',
    'org.apache.nifi.processors.standard.ForkRecord',
    'org.apache.nifi.processors.standard.GenerateFlowFile',
    'org.apache.nifi.processors.standard.GenerateRecord',
    'org.apache.nifi.processors.standard.GenerateTableFetch',
    'org.apache.nifi.processors.standard.GetFTP',
    'org.apache.nifi.processors.standard.GetFile',
    'org.apache.nifi.processors.standard.GetFileResource',
    'org.apache.nifi.processors.standard.GetSFTP',
    'org.apache.nifi.processors.standard.HandleHttpRequest',
    'org.apache.nifi.processors.standard.HandleHttpResponse',
    'org.apache.nifi.processors.standard.IdentifyMimeType',
    'org.apache.nifi.processors.standard.InvokeHTTP',
    'org.apache.nifi.processors.standard.JoinEnrichment',
    'org.apache.nifi.processors.standard.ListDatabaseTables',
    'org.apache.nifi.processors.standard.ListFTP',
    'org.apache.nifi.processors.standard.ListFile',
    'org.apache.nifi.processors.standard.ListSFTP',
    'org.apache.nifi.processors.standard.ListenFTP',
    'org.apache.nifi.processors.standard.ListenHTTP',
    'org.apache.nifi.processors.standard.ListenSyslog',
    'org.apache.nifi.processors.standard.ListenTCP',
    'org.apache.nifi.processors.standard.ListenUDP',
    'org.apache.nifi.processors.standard.ListenUDPRecord',
    'org.apache.nifi.processors.standard.LogAttribute',
    'org.apache.nifi.processors.standard.LogMessage',
    'org.apache.nifi.processors.standard.LookupAttribute',
    'org.apache.nifi.processors.standard.LookupRecord',
    'org.apache.nifi.processors.standard.MergeContent',
    'org.apache.nifi.processors.standard.MergeRecord',
    'org.apache.nifi.processors.standard.ModifyBytes',
    'org.apache.nifi.processors.standard.MonitorActivity',
    'org.apache.nifi.processors.standard.Notify',
    'org.apache.nifi.processors.standard.PackageFlowFile',
    'org.apache.nifi.processors.standard.ParseSyslog',
    'org.apache.nifi.processors.standard.ParseSyslog5424',
    'org.apache.nifi.processors.standard.PartitionRecord',
    'org.apache.nifi.processors.standard.PutDatabaseRecord',
    'org.apache.nifi.processors.standard.PutDistributedMapCache',
    'org.apache.nifi.processors.standard.PutEmail',
    'org.apache.nifi.processors.standard.PutFTP',
    'org.apache.nifi.processors.standard.PutFile',
    'org.apache.nifi.processors.standard.PutRecord',
    'org.apache.nifi.processors.standard.PutSFTP',
    'org.apache.nifi.processors.standard.PutSQL',
    'org.apache.nifi.processors.standard.PutSyslog',
    'org.apache.nifi.processors.standard.PutTCP',
    'org.apache.nifi.processors.standard.PutUDP',
    'org.apache.nifi.processors.standard.QueryDatabaseTable',
    'org.apache.nifi.processors.standard.QueryDatabaseTableRecord',
    'org.apache.nifi.processors.standard.QueryRecord',
    'org.apache.nifi.processors.standard.RemoveRecordField',
    'org.apache.nifi.processors.standard.RenameRecordField',
    'org.apache.nifi.processors.standard.ReplaceText',
    'org.apache.nifi.processors.standard.ReplaceTextWithMapping',
    'org.apache.nifi.processors.standard.RetryFlowFile',
    'org.apache.nifi.processors.standard.RouteOnAttribute',
    'org.apache.nifi.processors.standard.RouteOnContent',
    'org.apache.nifi.processors.standard.RouteText',
    'org.apache.nifi.processors.standard.SampleRecord',
    'org.apache.nifi.processors.standard.ScanAttribute',
    'org.apache.nifi.processors.standard.ScanContent',
    'org.apache.nifi.processors.standard.SegmentContent',
    'org.apache.nifi.processors.standard.SplitContent',
    'org.apache.nifi.processors.standard.SplitJson',
    'org.apache.nifi.processors.standard.SplitRecord',
    'org.apache.nifi.processors.standard.SplitText',
    'org.apache.nifi.processors.standard.SplitXml',
    'org.apache.nifi.processors.standard.TailFile',
    'org.apache.nifi.processors.standard.TransformXml',
    'org.apache.nifi.processors.standard.UnpackContent',
    'org.apache.nifi.processors.standard.UpdateCounter',
    'org.apache.nifi.processors.standard.UpdateDatabaseTable',
    'org.apache.nifi.processors.standard.UpdateRecord',
    'org.apache.nifi.processors.standard.ValidateCsv',
    'org.apache.nifi.processors.standard.ValidateJson',
    'org.apache.nifi.processors.standard.ValidateRecord',
    'org.apache.nifi.processors.standard.ValidateXml',
    'org.apache.nifi.processors.standard.Wait',
    'org.apache.nifi.processors.stateful.analysis.AttributeRollingWindow',
    'org.apache.nifi.processors.twitter.ConsumeTwitter',
    'org.apache.nifi.processors.websocket.ConnectWebSocket',
    'org.apache.nifi.processors.websocket.ListenWebSocket',
    'org.apache.nifi.processors.websocket.PutWebSocket',
    'org.apache.nifi.processors.windows.event.log.ConsumeWindowsEventLog',
    'org.apache.nifi.processors.workday.GetWorkdayReport',
    'org.apache.nifi.processors.zendesk.GetZendesk',
    'org.apache.nifi.processors.zendesk.PutZendeskTicket',
    'org.apache.nifi.redis.processor.PutRedisHashRecord',
    'org.apache.nifi.snmp.processors.GetSNMP',
    'org.apache.nifi.snmp.processors.ListenTrapSNMP',
    'org.apache.nifi.snmp.processors.SendTrapSNMP',
    'org.apache.nifi.snmp.processors.SetSNMP',
]

RESTRICTED = {
    'org.apache.nifi.cdc.mysql.processors.CaptureChangeMySQL',
    'org.apache.nifi.jms.processors.ConsumeJMS',
    'org.apache.nifi.jms.processors.PublishJMS',
    'org.apache.nifi.processors.groovyx.ExecuteGroovyScript',
    'org.apache.nifi.processors.script.ExecuteScript',
    'org.apache.nifi.processors.script.InvokeScriptedProcessor',
    'org.apache.nifi.processors.script.ScriptedFilterRecord',
    'org.apache.nifi.processors.script.ScriptedPartitionRecord',
    'org.apache.nifi.processors.script.ScriptedTransformRecord',
    'org.apache.nifi.processors.script.ScriptedValidateRecord',
    'org.apache.nifi.processors.standard.DeleteFile',
    'org.apache.nifi.processors.standard.ExecuteProcess',
    'org.apache.nifi.processors.standard.ExecuteStreamCommand',
    'org.apache.nifi.processors.standard.ExtractGrok',
    'org.apache.nifi.processors.standard.FetchFile',
    'org.apache.nifi.processors.standard.GetFile',
    'org.apache.nifi.processors.standard.GetFileResource',
    'org.apache.nifi.processors.standard.PutFile',
    'org.apache.nifi.processors.standard.TailFile',
    'org.apache.nifi.processors.standard.ValidateJson',
    'org.apache.nifi.processors.standard.ValidateXml',
}

DEPRECATED = {
    'org.apache.nifi.processors.asana.GetAsanaObject',
    'org.apache.nifi.processors.geohash.GeohashRecord',
    'org.apache.nifi.processors.network.ParseNetflowv5',
}
