"""Access to the harvested processor *rulebook* (relationships, ...).

NiFi's per-type rules — the relationship names, required properties, allowable
values — aren't available from any "describe type" endpoint; they only exist
once a processor is instantiated. ``make catalog`` harvests them (see
:func:`niflow.codegen._harvest_rules`) into the generated catalog, and this
module reads them back so the validator can check a flow with pure logic, no
push required.

Everything degrades gracefully: a catalog generated before harvesting (or
without write access) simply has no ``RELATIONSHIPS`` map, and lookups return
``None`` so callers fall back to their heuristic.
"""
from __future__ import annotations

import re
from typing import Dict, List, Optional, Tuple


def _catalog_table(name: str):
    try:
        from niflow.processors import catalog
    except Exception:  # pragma: no cover - catalog import should never fail
        return None
    return getattr(catalog, name, None) or None


def _service_catalog_table(name: str):
    """The same table from the generated *controller-service* catalog."""
    try:
        from niflow.services import catalog as service_catalog
    except Exception:  # pragma: no cover - catalog import should never fail
        return None
    return getattr(service_catalog, name, None) or None


def _typed_entry(name: str, type_str: str):
    """A generated table's entry for *type_str*, processors or services.

    Processor and controller-service FQCNs are disjoint, so a single lookup
    across both catalogs is unambiguous — and it means every property helper
    here works for services, which previously fell straight through to "not
    harvested" and skipped the compat join entirely.
    """
    for getter in (_catalog_table, _service_catalog_table):
        table = getter(name)
        if table and type_str in table:
            return table[type_str]
    return None


def _compat_table(name: str):
    """A table from the harvested 1.x compatibility module, or ``None``.

    ``compat_v1`` is generated by ``python -m niflow.codegen --compat`` against
    a 1.x instance; absent (not yet harvested), every cross-version lookup
    degrades to "unknown — don't translate".
    """
    try:
        from niflow.processors import compat_v1
    except Exception:
        return None
    return getattr(compat_v1, name, None) or None


def _compat_entry(name: str, type_str: str):
    """A ``compat_v1`` table entry for *type_str*, processor or service.

    Services live in the ``SERVICE_``-prefixed twins of each table.
    """
    for table_name in (name, f"SERVICE_{name}"):
        table = _compat_table(table_name)
        if table and type_str in table:
            return table[type_str]
    return None


def harvested_on_v1(type_str: str) -> bool:
    """Whether the 1.x compat harvest actually instantiated this type.

    ``DESCRIPTORS``/``PROPERTY_NAMES`` only carry types that *have* properties,
    so a type with none at all (``ForkEnrichment``, ``ExtractEmailAttachments``,
    every lookup service) used to be indistinguishable from one the harvest
    never saw — and "no data" makes every cross-version lookup degrade to
    "unknown, don't translate". ``TYPES``/``SERVICE_TYPES`` record the harvest's
    real reach, so "known to have nothing to translate" is now sayable.
    Absent tables (a compat module generated before this) return False, which is
    the old behaviour.
    """
    for table_name in ("TYPES", "SERVICE_TYPES"):
        table = _compat_table(table_name)
        if table and type_str in table:
            return True
    return False


def _version_map_entry(type_str: str):
    """This type's entry in the generated cross-version map, or ``None``.

    ``None`` means "the map has nothing to say about this type" — it wasn't
    harvested, or it exists on only one line. An empty dict means the opposite:
    the type was compared on both lines and its property surface is identical.
    That distinction is what lets callers tell "no differences" from "no data".
    """
    try:
        from niflow import version_map
    except Exception:
        return None
    for table in ("PROCESSOR_DIFF", "SERVICE_DIFF"):
        diff = getattr(version_map, table, None) or {}
        if type_str in diff:
            return diff[type_str]
    for table in ("PROCESSOR_TYPES_BOTH", "SERVICE_TYPES_BOTH"):
        if type_str in (getattr(version_map, table, None) or frozenset()):
            return {}
    return None


def _version_map_targets(major_version: int) -> bool:
    """Whether the generated map's *old* line is the major version asked about.

    The map is directional (harvested new-vs-old); using it to translate for a
    target it wasn't built against would be worse than not using it at all.
    """
    try:
        from niflow.version_map import VERSION_MAP_META
    except Exception:
        return False
    old = str(VERSION_MAP_META.get("old_version", ""))
    return old[:1].isdigit() and int(old.split(".", 1)[0]) == major_version


def relationships_for(
    type_str: str,
    props: Optional[Dict[str, object]] = None,
    major_version: Optional[int] = None,
) -> Optional[List[str]]:
    """The relationship names for a processor type, or ``None`` if not harvested.

    A return of ``None`` means "unknown — fall back to a heuristic"; an empty
    list means "known to have no relationships".

    Two things make a bare per-type set wrong, and both are answered here:

    * **the line matters.** The catalog is harvested from 2.x; a 1.x server can
      have a different set, and it is the server that refuses to start a
      processor whose relationship is unhandled. Pass ``major_version=1`` to get
      the 1.x set (``compat_v1.RELATIONSHIPS``) where one was harvested.
    * **properties matter.** ``UpdateAttribute`` has no ``set state fail``
      relationship until ``Store State`` is set to "Store state locally" — and
      then NiFi will not start it until that relationship is handled, on a flow
      ``validate`` called clean. Pass the processor's ``props`` to fold in the
      harvested :data:`CONDITIONAL_RELATIONSHIPS` overrides.
    """
    table = None
    if major_version == 1:
        table = _compat_table("RELATIONSHIPS")
    if table is None or type_str not in table:
        table = _catalog_table("RELATIONSHIPS")
    if not table or type_str not in table:
        return None
    base = list(table[type_str])
    return _apply_conditional(type_str, base, props, major_version)


def _apply_conditional(
    type_str: str,
    base: List[str],
    props: Optional[Dict[str, object]],
    major_version: Optional[int],
) -> List[str]:
    """Fold property-conditional relationship overrides into a base set.

    Each harvested entry is the FULL relationship set while one property holds
    one value, so an active override *replaces* the base set rather than adding
    to it (``RouteOnAttribute``'s non-default routing strategies collapse the
    dynamic relationships to matched/unmatched). Two active overrides are
    unioned — the harvest probes one property at a time and cannot know how a
    pair combines, and over-reporting a relationship the user must handle is
    the safe direction.
    """
    conditional = conditional_relationships_for(type_str, major_version)
    if not conditional or not props:
        return base
    props = canonical_properties(type_str, props)
    descriptors = descriptors_for(type_str) or {}
    active: List[List[str]] = []
    for name, by_value in conditional.items():
        value = props.get(name)
        if value in (None, ""):
            value = (descriptors.get(name) or {}).get("default")
        if isinstance(value, str) and value in by_value:
            active.append(list(by_value[value]))
    if not active:
        return base
    out: List[str] = list(active[0])
    for extra in active[1:]:
        out += [rel for rel in extra if rel not in out]
    return out


def conditional_relationships_for(
    type_str: str, major_version: Optional[int] = None
) -> Optional[Dict[str, Dict[str, tuple]]]:
    """``{property: {value: (relationships, ...)}}`` for a type, or ``None``.

    Harvested by setting each small-enum property to each of its values and
    reading the relationship list back (:func:`niflow.codegen._probe_relationships`),
    on both NiFi lines.
    """
    table = None
    if major_version == 1:
        table = _compat_table("CONDITIONAL_RELATIONSHIPS")
        if table is not None and type_str not in table:
            # The 1.x harvest ran and had nothing to say about this type; only
            # fall back to the 2.x table when there was no 1.x harvest at all.
            return None if type_str in (_compat_table("TYPES") or ()) else (
                _catalog_table("CONDITIONAL_RELATIONSHIPS") or {}).get(type_str)
    if table is None:
        table = _catalog_table("CONDITIONAL_RELATIONSHIPS")
    return table.get(type_str) if table else None


def primary_node_only(type_str: str) -> bool:
    """Whether NiFi pins this processor type to the primary node.

    ``@PrimaryNodeOnly`` types (ListFTP, ListSFTP, ...) are created with
    ``executionNode=PRIMARY`` whatever was asked for, and the server refuses
    ``ALL``, so the model's ``ALL`` default is not drift for them. Harvested
    from ``ProcessorDTO.executionNodeRestricted``, which both NiFi lines
    report; an un-harvested catalog simply has no set and this returns False.

    Both lines are consulted: the 1.24 harvest agrees with 2.7.2 on every type
    the two share and adds three that only exist on 1.x (``ListHDFS``,
    ``GetJMSTopic``, ``ListAzureBlobStorage``), so the union is exactly "pinned
    on the line you are talking to" without needing to know which line that is.
    """
    for getter, name in ((_catalog_table, "PRIMARY_NODE_ONLY"),
                         (_compat_table, "PRIMARY_NODE_ONLY")):
        table = getter(name)
        if table and type_str in table:
            return True
    return False


def descriptors_for(type_str: str) -> Optional[Dict[str, dict]]:
    """Harvested property descriptors for a type, or ``None`` if not harvested.

    Maps property name -> ``{required, default, allowable, service,
    dependencies, display}`` (only the keys that apply). ``None`` means
    "unknown — don't check properties for this type".
    """
    return _typed_entry("DESCRIPTORS", type_str)


def property_names_for(type_str: str) -> Optional[List[str]]:
    """All canonical property names for a type, or ``None`` if not harvested."""
    names = _typed_entry("PROPERTY_NAMES", type_str)
    return list(names) if names is not None else None


def descriptors_for_target(
    type_str: str, major_version: Optional[int] = None
) -> Dict[str, dict]:
    """Property descriptors as the *target* NiFi line reports them.

    :func:`descriptors_for` speaks the catalog's namespace (2.x). A 1.x server
    materialises properties 2.x does not have at all (``QueryRecord``'s
    ``cache-schema``, ``ConsumeJMS``'s ``Session Cache size``) and can give a
    shared property a different default (``FetchGoogleDrive``'s
    ``Google Spreadsheet Export Type`` defaults to ``text/csv`` on 1.24 and
    ``application/pdf`` on 2.7.2). Judging those against the 2.x table reads the
    effective default as ``None``, which is why the differ proposed unsetting a
    1.x-only property on every plan, forever.

    The 1.x table is re-keyed through the harvested renames first, so a property
    that merely changed name is not mistaken for a 1.x-only one, and it wins for
    the keys it covers — the live server is the one that gets to say what its
    own defaults are.
    """
    base = dict(descriptors_for(type_str) or {})
    if major_version != 1:
        return base
    v1 = _compat_entry("DESCRIPTORS", type_str)
    if not v1:
        return base
    renames = property_renames_for(type_str) or {}
    v1_by_canonical = {legacy: canonical for canonical, legacy in renames.items()}
    for name, entry in v1.items():
        base[v1_by_canonical.get(name, name)] = entry
    return base


# Types whose *dynamic properties become relationships* (RouteOnAttribute's
# property "hot" creates a relationship "hot"). The REST create response the
# harvest reads (ProcessorDTO) doesn't expose ``supportsDynamicRelationships``
# — only the 2.x ``/flow/processor-definition/...`` endpoint does, which the
# harvest doesn't call — so this is curated by hand as a documented last
# resort. Each entry is either ``None`` (dynamic properties are always
# relationships) or a gate ``{"property", "value"}``: the behaviour only
# applies while that property holds that value (its default), because the
# other routing strategies collapse the relationships to matched/unmatched.
DYNAMIC_RELATIONSHIP_TYPES: Dict[str, Optional[Dict[str, str]]] = {
    "org.apache.nifi.processors.standard.RouteOnAttribute": {
        "property": "Routing Strategy", "value": "Route to Property name"},
    "org.apache.nifi.processors.standard.RouteOnContent": None,
    "org.apache.nifi.processors.standard.RouteText": {
        "property": "Routing Strategy",
        "value": "Route to each matching Property Name"},
    "org.apache.nifi.processors.hl7.RouteHL7": None,
    "org.apache.nifi.processors.standard.QueryRecord": None,
}


def supports_dynamic_relationships(
    type_str: str, major_version: Optional[int] = None
) -> bool:
    """Whether a type's dynamic properties can create relationships.

    Harvested now (``DYNAMIC_RELATIONSHIPS``, set by probing one dynamic
    property and reading the relationship list back — which works on 1.x, whose
    ``/flow/processor-definition`` endpoint does not exist). The curated
    :data:`DYNAMIC_RELATIONSHIP_TYPES` stays as a floor so a stale or missing
    catalog never *loses* a type: the probe can only fail to confirm one (it
    does not confirm ``RouteHL7`` on 1.24, whose dynamic property must parse as
    an HL7 query before it counts), never wrongly invent one.
    """
    if type_str in DYNAMIC_RELATIONSHIP_TYPES:
        return True
    for getter in ((_compat_table,) if major_version == 1 else ()) + (_catalog_table,):
        table = getter("DYNAMIC_RELATIONSHIPS")
        if table and type_str in table:
            return True
    return False


def dynamic_relationships_for(
    type_str: str,
    props: Dict[str, object],
    major_version: Optional[int] = None,
) -> Optional[List[str]]:
    """Relationship names the processor's dynamic properties create, or ``None``.

    ``None`` means "don't treat dynamic property names as relationships" —
    either the type isn't a dynamic-relationship one, its routing strategy has
    been switched away from per-property routing (or is set via EL/parameters
    and can't be judged), or the catalog lacks the property-name table needed
    to tell real properties from dynamic ones. A list (possibly empty) means
    per-property routing is active and exactly those names are relationships.
    """
    if not supports_dynamic_relationships(type_str, major_version):
        return None
    props = canonical_properties(type_str, props or {})
    gate = DYNAMIC_RELATIONSHIP_TYPES.get(type_str)
    if gate is None and type_str in DYNAMIC_RELATIONSHIP_TYPES:
        pass  # curated as "always a relationship"
    elif gate is None:
        # Harvested type with no curated gate: a conditional override means the
        # per-property routing has been switched off, exactly like the gate.
        base = (_catalog_table("RELATIONSHIPS") or {}).get(type_str) or []
        if sorted(_apply_conditional(type_str, list(base), props, major_version)) \
                != sorted(base):
            return None
    if gate is not None:
        value = props.get(gate["property"])
        if value in (None, ""):
            descriptors = descriptors_for(type_str) or {}
            value = (descriptors.get(gate["property"]) or {}).get("default")
        if value != gate["value"]:
            return None
    names = property_names_for(type_str)
    if names is None:
        return None
    known = set(names)
    return sorted(k for k, v in props.items() if k not in known and v is not None)


# NiFi 2.x renamed many canonical property keys to match their display names
# (its migrateProperties machinery translates old keys on import, but the old
# names are exposed nowhere in the REST API). The renames niflow has actually
# hit are curated here; an entry only applies when the old key is NOT a real
# property of the type and the new key IS — so a 1.x catalog (where the old
# key is still canonical) is never corrupted.
LEGACY_PROPERTY_ALIASES = {
    "record-reader": "Record Reader",
    "record-writer": "Record Writer",
    "generate-ff-custom-text": "Custom Text",
    "character-set": "Character Set",
    "mime-type": "Mime Type",
    # ReplaceText (the guard keeps this off types that have their own
    # canonical "Regular Expression" property)
    "Regular Expression": "Search Value",
    # LogAttribute — 2.x dropped the "by" from the display name too, so the
    # cross-version display-name join can't discover these on its own.
    "attributes-to-log-regex": "Attributes to Log Regular Expression",
    "attributes-to-ignore-regex": "Attributes to Ignore Regular Expression",
}


# Renames the automatic matcher deliberately refuses to guess, confirmed by
# hand from the two descriptor harvests (see docs/version-compat.md, "Renames
# recovered by hand").
#
# ``niflow.versiondiff.detect_renames`` pairs a leftover property to exactly
# one counterpart on display name, then description, and only when the pairing
# is 1:1 in both directions. That is the right default — a wrong pairing writes
# a value onto the wrong property, which is worse than not translating — but it
# leaves genuine renames sitting in the ``only_new``/``only_old`` buckets as
# false alarms whenever key *and* display name *and* description all moved.
#
# Each entry below was accepted only on corroborating evidence: the same
# allowable-value set, the same default, the same required-ness/sensitivity,
# the same dependency on the same sibling property, the same ordinal position,
# and a description that still says the same thing. Keyed exactly like the
# generated map: ``{type: {new (2.x/catalog) key: old (1.x) key}}``.
#
# Both the generator (so the committed map, its counts and the report agree)
# and :func:`property_renames_for` (so translation works even against a stale
# or missing map) read this table — for controller services as well as
# processors, which is where a silent inert dynamic property hurts most.
CURATED_TYPE_RENAMES: Dict[str, Dict[str, str]] = {
    # --- processors ---
    # 2.x dropped the unit from the key; the unit itself did not change
    # (both lines document seconds) and the defaults match.
    "org.apache.nifi.processors.mqtt.ConsumeMQTT": {
        "Connection Timeout": "Connection Timeout (seconds)",
        "Keep Alive": "Keep Alive Interval (seconds)",
    },
    "org.apache.nifi.processors.mqtt.PublishMQTT": {
        "Connection Timeout": "Connection Timeout (seconds)",
        "Keep Alive": "Keep Alive Interval (seconds)",
    },
    # "The SQL select query to execute…" -> "The SQL query to execute…".
    "org.apache.nifi.processors.standard.ExecuteSQL": {
        "SQL Query": "SQL select query",
    },
    "org.apache.nifi.processors.standard.ExecuteSQLRecord": {
        "SQL Query": "SQL select query",
    },
    # Identical allowable set (TRACE…NONE) and default (ERROR).
    "org.apache.nifi.processors.standard.FetchFile": {
        "Permission Denied Log Level": "Log level when permission denied",
    },
    # 2.x moved the "(between 1 and 50)" range out of the name and into the
    # description; same default of 1.
    "org.apache.nifi.processors.aws.dynamodb.DeleteDynamoDB": {
        "Batch Items Per Request": "Batch items for each request (between 1 and 50)",
    },
    "org.apache.nifi.processors.aws.dynamodb.GetDynamoDB": {
        "Batch Items Per Request": "Batch items for each request (between 1 and 50)",
        "Json Document": "Json Document attribute",
    },
    "org.apache.nifi.processors.aws.dynamodb.PutDynamoDB": {
        "Batch Items Per Request": "Batch items for each request (between 1 and 50)",
        "Json Document": "Json Document attribute",
    },
    "org.apache.nifi.processors.aws.sns.PutSNS": {
        "Amazon Resource Name": "Amazon Resource Name (ARN)",
    },
    # Pure kebab-case -> display-name key; identical descriptor otherwise.
    "org.apache.nifi.processors.aws.kinesis.stream.PutKinesisStream": {
        "Max Message Buffer Size": "max-message-buffer-size",
    },
    # Identical allowable set (usm-json-file-path / usm-json-content /
    # usm-security-names) and the same dependants hang off it.
    "org.apache.nifi.snmp.processors.ListenTrapSNMP": {
        "USM Users Input Method": "snmp-usm-users-source",
    },
    # 1.x "Catalog Name"; 2.x renamed it and its description now reads "the
    # name of the database (or the name of the catalog…)". Same slot.
    "org.apache.nifi.processors.standard.PutDatabaseRecord": {
        "Database Name": "put-db-record-catalog-name",
    },
    # The credential slot survived the rename even though the credential kind
    # changed: Airtable deprecated API keys in favour of personal access
    # tokens and both go in the same header.
    "org.apache.nifi.processors.airtable.QueryAirtableTable": {
        "Personal Access Token": "api-key",
    },
    # --- controller services ---
    # 1.x display "Max Connection Lifetime", same default of -1. NOTE the 1.x
    # description says milliseconds where 2.x says "lifetime of a connection"
    # (a duration string) — the property is the same one, but check the value
    # after translating. Recorded under "behavioural drift" in the report.
    "org.apache.nifi.dbcp.DBCPConnectionPool": {
        "Maximum Connection Lifetime": "dbcp-max-conn-lifetime",
    },
    # 1.x display "Storage Account Key"; same sensitive credential.
    "org.apache.nifi.services.azure.storage.ADLSCredentialsControllerService": {
        "Account Key": "storage-account-key",
    },
}


def curated_renames_for(type_str: str) -> Dict[str, str]:
    """Hand-confirmed ``{new key: old key}`` renames for one type (may be empty)."""
    return dict(CURATED_TYPE_RENAMES.get(type_str) or {})


def canonical_properties(type_str: str, props: Dict[str, object]) -> Dict[str, object]:
    """Rewrite display-name and legacy property keys to canonical names.

    Users naturally write the name the NiFi UI shows ("Custom Text") — or a key
    from the NiFi version they migrated off — while the server keys the
    property map by the canonical name. Left as-is, a push can create a
    *dynamic* property with the intended one unset, and every diff shows
    phantom drift. Rewrites happen only when unambiguous:

    * a display name used by exactly one property maps to it (``CopyS3Object``
      has two properties both displayed as "Bucket" — those are left alone);
    * a curated legacy key maps only when the type really has the new key and
      really lacks the old one;
    * a key never overwrites one already set canonically;
    * unknown keys (true dynamic properties) and un-harvested types pass
      through untouched.
    """
    if not props:
        return props
    descriptors = descriptors_for(type_str) or {}
    names = property_names_for(type_str)
    aliases: Dict[str, str] = {}

    display_counts: Dict[str, int] = {}
    for name, entry in descriptors.items():
        display = entry.get("display")
        if display:
            display_counts[display] = display_counts.get(display, 0) + 1
    for name, entry in descriptors.items():
        display = entry.get("display")
        if display and display_counts[display] == 1:
            aliases[display] = name

    if names is not None:
        known = set(names)
        for old, new in LEGACY_PROPERTY_ALIASES.items():
            if old not in known and new in known:
                aliases.setdefault(old, new)

    renames = property_renames_for(type_str)
    if renames:
        # A live 1.x flow keys renamed properties by their old names; fold the
        # harvested renames in reverse so those normalise too.
        for canonical, legacy in renames.items():
            aliases.setdefault(legacy, canonical)

    if not aliases.keys() & props.keys():
        return props
    out: Dict[str, object] = {}
    for key, value in props.items():
        canonical = aliases.get(key, key)
        if canonical != key and canonical in props:
            canonical = key  # canonical key set explicitly elsewhere — keep both as-is
        out[canonical] = value
    return out


def property_renames_for(type_str: str) -> Optional[Dict[str, str]]:
    """Canonical (catalog) property name -> 1.x name, for renamed keys only.

    Prefers the generated cross-version map (:mod:`niflow.version_map`), which
    was built by diffing full descriptor harvests of both lines and matches
    renames on display name *and* description — so it catches pairs this
    module's own join cannot, and it covers controller services as well as
    processors. ``make version-map`` regenerates it.

    Without that map (never generated, or built against a different old line)
    this falls back to the original join: NiFi 2.x renamed many property keys
    to their display names, which the 1.x line still shows as ``displayName``
    over the old key, so joining the committed catalog against the harvested
    1.x compatibility table on display names (case-insensitively, and only
    where each side lacks the other's key) recovers the rename without curating
    every one. The curated ``LEGACY_PROPERTY_ALIASES`` fill in the few renames
    where the display name itself changed. ``None`` means "no 1.x data for this
    type — don't translate".
    """
    entry = _version_map_entry(type_str)
    if entry is not None and _version_map_targets(1):
        return _with_curated(type_str, dict(entry.get("renamed") or {}))

    v1_names_raw = _compat_entry("PROPERTY_NAMES", type_str)
    names = property_names_for(type_str)
    if v1_names_raw is None or names is None:
        # A type the 1.x harvest DID instantiate but which has no properties at
        # all (``ForkEnrichment``, the lookup services) is fully known — there
        # is simply nothing to rename. Saying "unknown" for those turned them
        # into fake holes in the compat data.
        if harvested_on_v1(type_str) and not (names or v1_names_raw):
            return {}
        return None
    known = set(names)
    v1_names = set(v1_names_raw)
    v1_descriptors = _compat_entry("DESCRIPTORS", type_str) or {}

    display_map: Dict[str, List[str]] = {}
    for v1_name in v1_names - known:
        display = (v1_descriptors.get(v1_name) or {}).get("display") or v1_name
        display_map.setdefault(display.lower(), []).append(v1_name)

    renames: Dict[str, str] = {}
    for canonical in known - v1_names:
        candidates = display_map.get(canonical.lower()) or []
        if len(candidates) == 1:
            renames[canonical] = candidates[0]
    for old, new in LEGACY_PROPERTY_ALIASES.items():
        if new in known and new not in v1_names and old in v1_names:
            renames.setdefault(new, old)
    return _with_curated(type_str, renames)


def _with_curated(type_str: str, renames: Dict[str, str]) -> Dict[str, str]:
    """Fold the hand-confirmed renames into an automatically derived set.

    Curated entries win: they were checked against the same two harvests by
    hand, so where the automatic matcher landed the same new key somewhere
    else it was guessing. Any other new key that pointed at the curated old
    key is dropped rather than left to fight over it — two keys translating to
    one would make the push order decide which value survives.
    """
    curated = CURATED_TYPE_RENAMES.get(type_str)
    if not curated:
        return renames
    for new_key, old_key in curated.items():
        for other_new, other_old in list(renames.items()):
            if other_old == old_key and other_new != new_key:
                del renames[other_new]
        renames[new_key] = old_key
    return renames


def properties_for_target(
    type_str: str, props: Dict[str, object], major_version: int
) -> Tuple[Dict[str, object], List[str]]:
    """Translate canonical property keys to what the target NiFi expects.

    The catalog — and therefore :func:`canonical_properties` — speaks the 2.x
    namespace; a 1.x server keys the same properties by their old names. For
    any target other than a 1.x one (or a type with no 1.x data) this is the
    identity. On a 1.x target:

    * a renamed key is sent under its 1.x name;
    * a catalog property with no 1.x counterpart is sent as ``None`` — an
      explicit unset, so it neither creates an unsupported property nor leaves
      one behind from an earlier push — and is reported in the second element;
    * dynamic keys (in neither namespace) pass through untouched.

    The "no counterpart" set comes from the generated version map when it
    covers this target, and otherwise from the compat-table join.
    """
    if major_version != 1 or not props:
        return props, []
    renames = property_renames_for(type_str)
    if renames is None:
        return props, []
    unsupported_names = _unsupported_on_target(type_str, major_version)
    if unsupported_names is None:
        # Fall back to the join's view: a catalog key that is neither renamed
        # nor present in the 1.x namespace has no counterpart.
        v1_names = set(_compat_entry("PROPERTY_NAMES", type_str) or ())
        known = set(property_names_for(type_str) or ())
        unsupported_names = {
            key for key in known
            if key not in renames and key not in v1_names
        }
    out: Dict[str, object] = {}
    unsupported: List[str] = []
    for key, value in props.items():
        target = renames.get(key, key)
        if target != key and target in props:
            target = key  # 1.x key set explicitly elsewhere — keep both as-is
        if target == key and key in unsupported_names:
            unsupported.append(key)
            value = None
        out[target] = value
    return out, unsupported


def _unsupported_on_target(type_str: str, major_version: int) -> Optional[set]:
    """Catalog-namespace keys the target line does not have, from the map.

    ``None`` means the map cannot answer (not generated, built against a
    different old line, or this type was never compared) — callers fall back
    to the compat-table join. An empty set means "compared, nothing missing",
    which is a genuine answer and must not be confused with the former.
    """
    if not _version_map_targets(major_version):
        return None
    entry = _version_map_entry(type_str)
    if entry is None:
        return None
    return set(entry.get("only_new") or ())


_KEY_SEPARATORS = re.compile(r"[-_ ]+")


def _normalised_key(key: str) -> str:
    """A property key with case and ``-``/``_``/space separators removed.

    Deliberately *not* ``.``: attribute-style dynamic keys (``mime.type`` on an
    UpdateAttribute) are the user's own names and must never be mistaken for a
    real property (``Mime Type``) they merely resemble.
    """
    return _KEY_SEPARATORS.sub("", key).lower()


def near_miss_properties(type_str: str, props: Dict[str, object]) -> Dict[str, str]:
    """``{key written: property it almost certainly means}`` for one component.

    ``max-bin-age`` is not a MergeContent property on *either* line — both key
    it ``Max Bin Age`` — so NiFi accepts it as a **dynamic** property, does
    nothing with it, and marks the processor invalid ("'max-bin-age' ... is not
    a supported property"). `niflow validate` passed it clean, which is how it
    reached a work server; the same shape catches any key carried over from an
    older NiFi, a hand-edit, or a doc that kebab-cased a display name.

    A key qualifies only when it is a property of neither namespace (2.x
    catalog or 1.x compat) and normalises onto *exactly one* real property of
    the same type in both directions — so a genuine dynamic property, which
    resembles nothing the type declares, is never flagged. Un-harvested types
    answer ``{}``: nothing is known about them, and guessing there would be the
    false positive that teaches people to ignore the check.
    """
    if not props:
        return {}
    catalog_names = set(property_names_for(type_str) or ())
    v1_names = set(_compat_entry("PROPERTY_NAMES", type_str) or ())
    known = catalog_names | v1_names
    if not known:
        return {}
    by_norm: Dict[str, List[str]] = {}
    for name in sorted(known):
        by_norm.setdefault(_normalised_key(name), []).append(name)
    written = [key for key in props if key not in known]
    out: Dict[str, str] = {}
    for key in written:
        norm = _normalised_key(key)
        candidates = by_norm.get(norm) or []
        # Two names normalising the same way across the two namespaces are the
        # same property under two spellings (2.x "Maximum Number of Bins" vs
        # 1.x "Maximum number of Bins") — suggest the catalog's, which is what
        # the flow should say. Two *within* one namespace would be genuine
        # ambiguity, and nothing is suggested there.
        preferred = [name for name in candidates if name in catalog_names] or candidates
        # 1:1 the other way too — two keys in the flow normalising onto the
        # same property means the flow, not the catalog, needs reading.
        if len(preferred) == 1 and sum(
                1 for other in written if _normalised_key(other) == norm) == 1:
            out[key] = preferred[0]
    return out


def unsupported_properties(
    type_str: str, props: Dict[str, object], major_version: int
) -> List[str]:
    """Which of *props* are real properties the target line does not have.

    The read-only twin of :func:`properties_for_target` for callers that want
    to *report* rather than translate (validate, doctor). Keys are canonicalized
    first, so a flow written with display-name or legacy keys is judged on what
    it actually means. Dynamic properties — keys in neither namespace — are the
    user's own and are never flagged.
    """
    if not props:
        return []
    unsupported_names = _unsupported_on_target(type_str, major_version)
    if unsupported_names is None:
        _, unsupported = properties_for_target(
            type_str, canonical_properties(type_str, props), major_version
        )
        return sorted(unsupported)
    canonical = canonical_properties(type_str, props)
    return sorted(set(canonical) & unsupported_names)
